{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.9.9/json-schema-serialization-0.9.9.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.9.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-linuxx64-0.9.9.klib",
          "size": 88256,
          "sha512": "24556a9db2900941b499f987d4bbee563b469f9d5a4e2d18d07ad8f5911d1e79b94a910b9d6e43c5a14d886024e4ecab9057563d045eaf6ade0bb7c53a67f764",
          "sha256": "c209f8965d8eb0803de0b5131671a4f451a625c074a9719ec3b0843cdda5027b",
          "sha1": "4b072bfbb90fed278068486b064cc6ad1b866a90",
          "md5": "8e5ce2df095729e6e2a6940c98090a10"
        }
      ]
    }
  ]
}
