{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.9/json-schema-serialization-0.8.9.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-jvm-0.8.9.jar",
          "url": "json-schema-serialization-jvm-0.8.9.jar",
          "size": 143803,
          "sha512": "f9d21acba8a36b952011ca0d9d2032606cc5adbfd0c814ebcb7140569a7b6b2c1dd22c9c3d9fea17040a1fbb3989bdde8c9d82b5e831870e8bbbb7d0d2b4d8b7",
          "sha256": "1d9161ab9a736129b2157047f3a88c44bfc721cc90d791e76183739e93fba508",
          "sha1": "534fa8baad68d303b71f24ec2dea45d2c7e1ba9c",
          "md5": "946ac56d650747ad3dc175d271ddd8fc"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-jvm-0.8.9.jar",
          "url": "json-schema-serialization-jvm-0.8.9.jar",
          "size": 143803,
          "sha512": "f9d21acba8a36b952011ca0d9d2032606cc5adbfd0c814ebcb7140569a7b6b2c1dd22c9c3d9fea17040a1fbb3989bdde8c9d82b5e831870e8bbbb7d0d2b4d8b7",
          "sha256": "1d9161ab9a736129b2157047f3a88c44bfc721cc90d791e76183739e93fba508",
          "sha1": "534fa8baad68d303b71f24ec2dea45d2c7e1ba9c",
          "md5": "946ac56d650747ad3dc175d271ddd8fc"
        }
      ]
    }
  ]
}
