{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.28/json-schema-serialization-0.8.28.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.28",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-jvm-0.8.28.jar",
          "url": "json-schema-serialization-jvm-0.8.28.jar",
          "size": 153453,
          "sha512": "83807941885f96be45a35be31b010d375990ac9166bbfe428a9456d6ae9dcde3181c9552743ff6af25f046f7c61db06dfb1528c44a6ae74838e3ae2d7dc51330",
          "sha256": "1a7215630b6ba5fc22f3b15ffe6ed021203581ad8c575d27b25eb2e02b38ac00",
          "sha1": "ffbfc28b3dad2fa4a24fa57c5736f4f921807344",
          "md5": "2cbb73c137b9b2172bf6fc79b07bc41a"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-jvm-0.8.28.jar",
          "url": "json-schema-serialization-jvm-0.8.28.jar",
          "size": 153453,
          "sha512": "83807941885f96be45a35be31b010d375990ac9166bbfe428a9456d6ae9dcde3181c9552743ff6af25f046f7c61db06dfb1528c44a6ae74838e3ae2d7dc51330",
          "sha256": "1a7215630b6ba5fc22f3b15ffe6ed021203581ad8c575d27b25eb2e02b38ac00",
          "sha1": "ffbfc28b3dad2fa4a24fa57c5736f4f921807344",
          "md5": "2cbb73c137b9b2172bf6fc79b07bc41a"
        }
      ]
    }
  ]
}
