{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.26/json-schema-serialization-0.8.26.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-mingwx64-0.8.26.klib",
          "size": 74656,
          "sha512": "9080ffc38c5e54ab83e1450801af899eb729eda03bc83a6ea0fde6d4973aea6d3e55cd0bcb24d71a0ed8938bd778f97c89be72d388bf7931cd6f8b291e91b0be",
          "sha256": "59893bf15b21eee60e76fd0d6de9a6abd78e62793a248c07b23decf6b0191b00",
          "sha1": "6af58bdc6c8891a9bd400316b6b1b77a8fc995ca",
          "md5": "2137166072a039c44b9d53318e263af7"
        }
      ]
    }
  ]
}
