{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.5/json-schema-serialization-0.8.5.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-macosx64-0.8.5.klib",
          "size": 71353,
          "sha512": "00a8fe8ad15a00684fdd01efc77416b78a8707548d90a73debc82fd1b3194c139a166fe937084a16c075cd1befb0362c7eb7e353db32b8645cfa5f260b3c56a5",
          "sha256": "4b5b84a17e75f9927a2145e76fdf19d53cdd0ac4058114834a691c71b3f7d3b6",
          "sha1": "ab3318c52d7ab8de2d574ccf82a69eb90043f430",
          "md5": "960f89595f3a181456fe020518de4c94"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-macosx64-0.8.5-metadata.jar",
          "url": "json-schema-serialization-macosx64-0.8.5-metadata.jar",
          "size": 261,
          "sha512": "e540cf63d54c5fdd5916b15778187e9436725c358b1bcf5eb28c3b3583582c710a2faeced4ad722224f3f708df11b80fc4f4ea2c9512a720cee164396dfa5713",
          "sha256": "9450338597c061c2b8585901059c99dfbb08079bc634a4bde4f9a85c145943ee",
          "sha1": "b701ff106eb784ddd6b2a4e51fec589a9a14e20a",
          "md5": "2cb7ef1a646158b8383a32693b63d82c"
        }
      ]
    }
  ]
}
