{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.15/json-schema-serialization-0.8.15.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-linuxx64-0.8.15.klib",
          "size": 73654,
          "sha512": "dc53ce6a65d899ceef9144d14959109e46dfbee31422140a3d2182610629a19820fa88fdf6d76f792fc8cf1ffe6f8500d26f99885bf3c1b0eb7f1ebb27fc9272",
          "sha256": "501c40c8a36b509d64229c316ba338a383fad0ec88717b712bdd814ff2b9c103",
          "sha1": "56b8e2f679e56c58d418e97374a6a613c0bd82ce",
          "md5": "1bd7146b959c66c3d472f48bad7effc1"
        }
      ]
    }
  ]
}
