{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.26/json-schema-serialization-0.8.26.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-linuxx64-0.8.26.klib",
          "size": 74656,
          "sha512": "d3aaed5b7ea239d294117ff815e8ddec4285db6b54befaaee17bf043310f701bdb6f9c6ef1e2b16d8fbf248fd317f7b8aff49ab60dc9de94503050c551df1c8e",
          "sha256": "758cfde29efa318d2d43ea58026fa82412dad815b5aa15d26483f5459dac5203",
          "sha1": "8da16b073252ff18bde8d9c7480cd90c8e096fb0",
          "md5": "509b3be9fb1559c86b62d4d034720deb"
        }
      ]
    }
  ]
}
