{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.3/json-schema-serialization-0.8.3.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-mingwx64-0.8.3.klib",
          "size": 71004,
          "sha512": "06a45b116b97dfbba99c48554bb4d1f0950e7c4a0a757f66f0ad744ad04923c59848189a93eb04a12cafe09ce98da910dfc8aac7c473b6c2a9078d8dae044bc6",
          "sha256": "a02670218faca6ec08315d91a3d3bed3e2fbb750d6233342358afd4610c5158d",
          "sha1": "e6e3cb5be3bc24cca605e1c495600e99cb823c48",
          "md5": "efcb45a31ab57a860926e1b8878bd0dd"
        }
      ]
    }
  ]
}
