{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.20/json-schema-serialization-0.8.20.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-linuxx64-0.8.20.klib",
          "size": 73834,
          "sha512": "681d866ceabfd696bec96001cb15583b5761f8d847abaf0b4f901d23be926dd13b9bcbd4131a797fd45fbab828ce386c4274032884d262c4b19f4ed11874523a",
          "sha256": "c87ffaa23ff36cc5470b3260adb3ef529a85b1202229f05040e6b225fc90253a",
          "sha1": "5eae962a684b9c6e8b2ae90b8a6d909ea69c384c",
          "md5": "05aff05befd7f09dedc675ff17a3aabf"
        }
      ]
    }
  ]
}
