{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.9.1/json-schema-serialization-0.9.1.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-iosx64-0.9.1.klib",
          "size": 84786,
          "sha512": "432f58c4dfd0a150348b1d1dec60ce5ac07d8cf4c55b1cc5833fd5635d05fabd4da18e7df74e82d973f7be1cc08819046743e5181bb4fd5fd621238edb16d9bc",
          "sha256": "ca00fbf506023f7993e07d1f372628077fbfef823b1f1fb1e523f7215b8c3d7b",
          "sha1": "ba76ec7e06f8ab13bcfe1e554066c19a0a949665",
          "md5": "6b78b4af4c5280fc4f51d425c202c413"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-iosx64-0.9.1-metadata.jar",
          "url": "json-schema-serialization-iosx64-0.9.1-metadata.jar",
          "size": 261,
          "sha512": "a5047f76d1d3b7754e83d5f29cdfe5998963fc209e24ac4c31959d54522ba409581670b48f6a888f432d56073e9a1f4d9a6d84de36b22d9840353e101aba0b8f",
          "sha256": "3714bcf4ecb24c32fc59cf86151992b88f0c8f5a4bf0b2700c9ed9af0e39c60d",
          "sha1": "4ceedebf0ef98c18a2461b47c78defc74954dfd4",
          "md5": "417e2e60ca8abc028a05c8046d890677"
        }
      ]
    }
  ]
}
