{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.9.5/json-schema-serialization-0.9.5.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.9.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-release.aar",
          "url": "json-schema-serialization-android-0.9.5.aar",
          "size": 152121,
          "sha512": "7a73aa6da728c53f98f522c8352f385545f79150781d11357cf7c0265d5bc258ff579f376e6ce22bbac51036ca5a26ea0d11e596cbe519b93182f3126605bc6a",
          "sha256": "a0302565022a36d7fd7cadd04fda5e375354062b12bae9c165a4dd21c9dcb68c",
          "sha1": "ebdf8bf0a9dbfa7d1b40b62a28ce33412ab18fd7",
          "md5": "6e8dcdab26b1fef0df6bdc05ed5145c6"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-release.aar",
          "url": "json-schema-serialization-android-0.9.5.aar",
          "size": 152121,
          "sha512": "7a73aa6da728c53f98f522c8352f385545f79150781d11357cf7c0265d5bc258ff579f376e6ce22bbac51036ca5a26ea0d11e596cbe519b93182f3126605bc6a",
          "sha256": "a0302565022a36d7fd7cadd04fda5e375354062b12bae9c165a4dd21c9dcb68c",
          "sha1": "ebdf8bf0a9dbfa7d1b40b62a28ce33412ab18fd7",
          "md5": "6e8dcdab26b1fef0df6bdc05ed5145c6"
        }
      ]
    }
  ]
}
