{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.23/json-schema-serialization-0.8.23.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-mingwx64-0.8.23.klib",
          "size": 74285,
          "sha512": "ac86335abc25114398ad78c4db503ae8cf48f5afd679157a7444c1ac0771eff4dfd39e83fbe047a4b70ca2ca851da38ca41c46cdcd2ad65ce820314b0fdeff5d",
          "sha256": "9d6a0fae5c0c4155db1a88b153d472ad4e684de82049ff91fde5f6be3e7d3fa8",
          "sha1": "23c4bd3c7a02485113c40583a7d1a98056b700f1",
          "md5": "9c89779876e7866e9881ff3057587de3"
        }
      ]
    }
  ]
}
