{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.21/json-schema-serialization-0.8.21.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-debug.aar",
          "url": "json-schema-serialization-android-debug-0.8.21.aar",
          "size": 141871,
          "sha512": "53870bb859767bc38e8dfe7cb0ce8f60cc5950da22a8bf2b51370484ae8e7a439abd52dc07e88738950bfa07f51e1b1dffee430ac7cdb92d8a5437ae26d4c1b8",
          "sha256": "c203001e0c5d133fccce15ef8f9fb09d5accef93e523208600894fee8c781c58",
          "sha1": "cc7b7e2633a8dcb61ed45fc45190020426b465d2",
          "md5": "bdc64ce13980a8b45cb79b5958df0a05"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-debug.aar",
          "url": "json-schema-serialization-android-debug-0.8.21.aar",
          "size": 141871,
          "sha512": "53870bb859767bc38e8dfe7cb0ce8f60cc5950da22a8bf2b51370484ae8e7a439abd52dc07e88738950bfa07f51e1b1dffee430ac7cdb92d8a5437ae26d4c1b8",
          "sha256": "c203001e0c5d133fccce15ef8f9fb09d5accef93e523208600894fee8c781c58",
          "sha1": "cc7b7e2633a8dcb61ed45fc45190020426b465d2",
          "md5": "bdc64ce13980a8b45cb79b5958df0a05"
        }
      ]
    }
  ]
}
