{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-metadata-0.8.11.jar",
          "url": "json-schema-serialization-0.8.11.jar",
          "size": 12084,
          "sha512": "0ea10a4a845c115dc84702cdb71cf90a69e71a975aaf373c497955d8a37e7e2d77914b45b269253798d30849ec29b67fae634cc6dbaaa469f0f8fd4d55a19e38",
          "sha256": "08459e1585990d3355d858ea4670f3947f230534683043df4878461f15fa5a73",
          "sha1": "9d9cd419375e1978d99e56fba1c4c00c2aef32fd",
          "md5": "f7fd677340c0ebcff83c8c532099b630"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../json-schema-serialization-android-debug/0.8.11/json-schema-serialization-android-debug-0.8.11.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-android-debug",
        "version": "0.8.11"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../json-schema-serialization-android-debug/0.8.11/json-schema-serialization-android-debug-0.8.11.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-android-debug",
        "version": "0.8.11"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../json-schema-serialization-android/0.8.11/json-schema-serialization-android-0.8.11.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-android",
        "version": "0.8.11"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../json-schema-serialization-android/0.8.11/json-schema-serialization-android-0.8.11.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-android",
        "version": "0.8.11"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../json-schema-serialization-iosarm64/0.8.11/json-schema-serialization-iosarm64-0.8.11.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-iosarm64",
        "version": "0.8.11"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../json-schema-serialization-iosarm64/0.8.11/json-schema-serialization-iosarm64-0.8.11.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-iosarm64",
        "version": "0.8.11"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../json-schema-serialization-iossimulatorarm64/0.8.11/json-schema-serialization-iossimulatorarm64-0.8.11.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-iossimulatorarm64",
        "version": "0.8.11"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../json-schema-serialization-iossimulatorarm64/0.8.11/json-schema-serialization-iossimulatorarm64-0.8.11.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-iossimulatorarm64",
        "version": "0.8.11"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../json-schema-serialization-iosx64/0.8.11/json-schema-serialization-iosx64-0.8.11.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-iosx64",
        "version": "0.8.11"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../json-schema-serialization-iosx64/0.8.11/json-schema-serialization-iosx64-0.8.11.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-iosx64",
        "version": "0.8.11"
      }
    },
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../json-schema-serialization-js/0.8.11/json-schema-serialization-js-0.8.11.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-js",
        "version": "0.8.11"
      }
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../json-schema-serialization-js/0.8.11/json-schema-serialization-js-0.8.11.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-js",
        "version": "0.8.11"
      }
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../json-schema-serialization-js/0.8.11/json-schema-serialization-js-0.8.11.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-js",
        "version": "0.8.11"
      }
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../json-schema-serialization-js/0.8.11/json-schema-serialization-js-0.8.11.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-js",
        "version": "0.8.11"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../json-schema-serialization-jvm/0.8.11/json-schema-serialization-jvm-0.8.11.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-jvm",
        "version": "0.8.11"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../json-schema-serialization-jvm/0.8.11/json-schema-serialization-jvm-0.8.11.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-jvm",
        "version": "0.8.11"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../json-schema-serialization-linuxx64/0.8.11/json-schema-serialization-linuxx64-0.8.11.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-linuxx64",
        "version": "0.8.11"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../json-schema-serialization-macosx64/0.8.11/json-schema-serialization-macosx64-0.8.11.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-macosx64",
        "version": "0.8.11"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../json-schema-serialization-macosx64/0.8.11/json-schema-serialization-macosx64-0.8.11.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-macosx64",
        "version": "0.8.11"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../json-schema-serialization-mingwx64/0.8.11/json-schema-serialization-mingwx64-0.8.11.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-mingwx64",
        "version": "0.8.11"
      }
    }
  ]
}
