{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.9.6/json-schema-serialization-0.9.6.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.9.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-linuxx64-0.9.6.klib",
          "size": 85260,
          "sha512": "adce27ab61b5f7c5ce23ea7a5b534e08875422be6621c5f24883f23f6cbf2ae4b3784033866fefd37258650ea599ad9cca00fc446c47950c91334b5c75aba8b9",
          "sha256": "2a6f790b3d7b7c5440460d85a6b3cfadd03177461dee67f53cfb2ee6de1a4d04",
          "sha1": "0a31fe6097ea812ea99d89809b0fb2148376eea1",
          "md5": "92a545103354ecb7e33e00da3e3118ae"
        }
      ]
    }
  ]
}
