{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.5/json-schema-serialization-0.8.5.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-mingwx64-0.8.5.klib",
          "size": 71353,
          "sha512": "364c150e64a307e139a357e41e7b5997ec0eefa073a231ced041a4e7f2acde655943b76696234e36bcc07531c625830730c0d76d198bff72713191324fe6cbb5",
          "sha256": "ff57496657758688444262de771df04916ebfe55704565bc2fc1409c23e4bc38",
          "sha1": "3d906eecd913ecf7abf0f8988b834f87f4a649c4",
          "md5": "21090f00bf03aa7a6b30e42eb67eb744"
        }
      ]
    }
  ]
}
