{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.27/json-schema-serialization-0.8.27.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-jvm-0.8.27.jar",
          "url": "json-schema-serialization-jvm-0.8.27.jar",
          "size": 153949,
          "sha512": "450f5b7b2f1c103a54e740d113fc59eeb62bee962003f1a31f0594e15fad6e33b043c8c2b3b1b1bf32f196234b1b1b0f81de9e7114084c2db445430fc0855e8e",
          "sha256": "b4808b1b7cc33ba00bdfd0df0104dce0f5e813a8ff183d60cc2798fc88f68cc4",
          "sha1": "5b14ddf9247fdb989ada3559a27c51a3087433f4",
          "md5": "50c43d30ee79695fb457dd944fc50e61"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-jvm-0.8.27.jar",
          "url": "json-schema-serialization-jvm-0.8.27.jar",
          "size": 153949,
          "sha512": "450f5b7b2f1c103a54e740d113fc59eeb62bee962003f1a31f0594e15fad6e33b043c8c2b3b1b1bf32f196234b1b1b0f81de9e7114084c2db445430fc0855e8e",
          "sha256": "b4808b1b7cc33ba00bdfd0df0104dce0f5e813a8ff183d60cc2798fc88f68cc4",
          "sha1": "5b14ddf9247fdb989ada3559a27c51a3087433f4",
          "md5": "50c43d30ee79695fb457dd944fc50e61"
        }
      ]
    }
  ]
}
