{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.12/json-schema-serialization-0.8.12.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-mingwx64-0.8.12.klib",
          "size": 73716,
          "sha512": "ddca84e3f15bbfde559a6df567f9adb376d36aaaa4394ae4418c0a8e6b8b505e1fe4333e435d34eaebfef578d95ce7d8c284b8875bd3042f582029b99fc7d6ce",
          "sha256": "5272265b4f2585512a8f702194a0f1e2c10596ff81c18e18fe29c0b1cd358b72",
          "sha1": "f120cad25232c963ad68fce5e0474174d8a773e0",
          "md5": "8194a5cc8776c0ad8d99bd2763e1c304"
        }
      ]
    }
  ]
}
