{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.19/json-schema-serialization-0.8.19.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-mingwx64-0.8.19.klib",
          "size": 73809,
          "sha512": "0cc4a77b1190203e5371305e87661153a02b00ae89779e584371243d6e8cb41e2a91d49576105e804981ed8339149a67f7e4b5f1376466e9557ede5cc597ae07",
          "sha256": "8bc876d71d91d21dd1f9037f02fb409d6e26f904613366dafb1eb4aa39959bdd",
          "sha1": "a6d8a71d73b23faa24580c72675e1c7249306125",
          "md5": "1ee463d0a3bc50295b78ad9449b7b6ee"
        }
      ]
    }
  ]
}
