{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.18/json-schema-serialization-0.8.18.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-mingwx64-0.8.18.klib",
          "size": 73832,
          "sha512": "5a45d38c240e33250d7efed7bdae7b2443029802e6fd794c9a7f5f24f883acc9a9c56711c575469990e516ffeddacb8af098bf1f36ceec3e8ef4a7059e20c466",
          "sha256": "50e80813b70f449dea279c1a645d07866aeee51aa3260448712af143c0a17121",
          "sha1": "098dba37a2b98903fcdb90b2ed91ef44b113de37",
          "md5": "25b81111b2d40cc73721dae509765787"
        }
      ]
    }
  ]
}
