{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.10/json-schema-serialization-0.8.10.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-linuxx64-0.8.10.klib",
          "size": 73591,
          "sha512": "b40e13c71855610f0ed08cce2df8f97f9ee86aee7b3c2a4b3fbb1bbc6239e0b40e1b13792fa7f18767715f46ecd068df8fce2aa78850b53ae01e8f14afae523d",
          "sha256": "4f7a06024d258d3533e3868d9468be6a4de47eed78f81d82e876735e63f4813e",
          "sha1": "39ce0b9f98a47c5153ce54e0a266cb0714f01d2f",
          "md5": "871a7b2c7c0e6abed105b0c5ae9d5a81"
        }
      ]
    }
  ]
}
