{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.11/json-schema-serialization-0.8.11.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-macosx64-0.8.11.klib",
          "size": 73715,
          "sha512": "faa855d3c133db93a9d56c0bfe60477a89ce19cb489c7bbed64380cb998116d7bda74b606531ae176a0c3282fdd1e88d3075669c1c6a81820cc6acbe129acf74",
          "sha256": "f72586d4bd5fde1befb6c6272091d532db535cb4f8638f0abf12e6e8d35985c9",
          "sha1": "23bdd33ad7c0b349c4b452a045b552196fa27664",
          "md5": "3677de98694d7cf61b1fb54c6e319519"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-macosx64-0.8.11-metadata.jar",
          "url": "json-schema-serialization-macosx64-0.8.11-metadata.jar",
          "size": 261,
          "sha512": "79a0f98c6cc397c052b815f7b4bf175d44c702a7f49c5a098ee9a02563eb3d03527a88a3a021e98f8b69b3a30f0aff4ae39fe68067732a496b15ffca57ec4f73",
          "sha256": "9ef63ba13a135f3376bb1b0ef9e221856f41c4860fbecb2b94dfda98453e0354",
          "sha1": "2e4305d74ff8458ee072c4e8c68064f44cb67031",
          "md5": "7ea2d50529f79f495b2bea2fc2a19568"
        }
      ]
    }
  ]
}
