{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.2/json-schema-serialization-0.8.2.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-linuxx64-0.8.2.klib",
          "size": 70790,
          "sha512": "38caa482f39d6fb4ba0c304f4e8b726a437b2bd0ed8f5a5a4b254bb30631fdf85ebcbf2cfb82e8c825bc2fce1d6313ce4a76e3ff544e33e2c33bb50dc40138c5",
          "sha256": "3d4e59a91eb2b18b731ab55798bdc03cc5ce1942fd2b1311a841762ab0a736f9",
          "sha1": "76a9bc4d83fa77d4eaa2106ca1b7ccb3d639baa6",
          "md5": "abce7aec810a0b63a8e5643a13032ba9"
        }
      ]
    }
  ]
}
