{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.2/json-schema-serialization-0.8.2.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-iosx64-0.8.2.klib",
          "size": 70772,
          "sha512": "8c2d31901c9c82ac2c336cb1adf424a3e7e8758d4db898987c6cda65cfc2489de4c91b41c761c8ed6ec540141a67d5e8e177fd29701e1d4c0aec693d216da674",
          "sha256": "ebfdae93e20aeee031dc02b0acfd857c3ec4e2ee1835036776d9fe2a5fe7aeb0",
          "sha1": "93bba60c166172569ebc36261dadd779281cb783",
          "md5": "7aad55875eac3902c1bccc8b09044b98"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-iosx64-0.8.2-metadata.jar",
          "url": "json-schema-serialization-iosx64-0.8.2-metadata.jar",
          "size": 261,
          "sha512": "09f4c5bbaae5080a49650e339b4c74ebd5fc8a2c837a097753e3e367b93461fadcd110097fa263eb2cf12eec722368f0ec9c63ca1500d36ebce214be05ae686a",
          "sha256": "17b43a0931ec6fa31951f6d826b66c6b629295905ca4e62e112541a2b219adaf",
          "sha1": "aea8f001e30ffc555f2e0f7445e082a2fcdb3787",
          "md5": "99512047ae7b7f6bdf7aa499f700ddb2"
        }
      ]
    }
  ]
}
