{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.9.0/json-schema-serialization-0.9.0.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-linuxx64-0.9.0.klib",
          "size": 83846,
          "sha512": "a32ce5c2ad7e79e98828135e4fceb690155085597a97f1877571babe378b83d68447120a2c2c88f01797f220c1a9c0eb2a3c23b8ecc47cf42ebbf23f8dbb3748",
          "sha256": "7b713c61e2eebd3b46f7a06d11bba8070980c45facd6759b19a9a7411905d727",
          "sha1": "2290490be545b0a0149d79f0677fcdbd0f2cbec4",
          "md5": "5518762ebfd25e5925e7118389a39908"
        }
      ]
    }
  ]
}
