{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.28/json-schema-serialization-0.8.28.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.28",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-jslegacy-0.8.28.jar",
          "url": "json-schema-serialization-js-0.8.28.jar",
          "size": 42380,
          "sha512": "9e71a83a0c742e29dc30faf23bdac3199c4547543297a1c5eaf640009ba303971dbeaf85a83beb0ea69a4c2f317d690a6edc9cb2e77e7dcb86ac9f11ec07581c",
          "sha256": "2d8dd47e11e4abec06370040a2288dc3c3667d7cf0885d4141bb9da72b583c79",
          "sha1": "69c348067582d8f9c3e37cb1052dd1d1a5214a84",
          "md5": "cb053464695116afa5901363f2db9f21"
        }
      ]
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-jslegacy-0.8.28.jar",
          "url": "json-schema-serialization-js-0.8.28.jar",
          "size": 42380,
          "sha512": "9e71a83a0c742e29dc30faf23bdac3199c4547543297a1c5eaf640009ba303971dbeaf85a83beb0ea69a4c2f317d690a6edc9cb2e77e7dcb86ac9f11ec07581c",
          "sha256": "2d8dd47e11e4abec06370040a2288dc3c3667d7cf0885d4141bb9da72b583c79",
          "sha1": "69c348067582d8f9c3e37cb1052dd1d1a5214a84",
          "md5": "cb053464695116afa5901363f2db9f21"
        }
      ]
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-jsir-0.8.28.klib",
          "url": "json-schema-serialization-js-0.8.28.klib",
          "size": 73626,
          "sha512": "8a59a89e81adb68845cfc194234b738323bd6072ace4b244e919f42cdaad5093ec4ea75bb36238e90117250eca296d9f177dba642c1f411d98a9b362087095f5",
          "sha256": "cdec176483f126ce26158cf130f7592d2b05e078bd6e33548d80fe19c93531bf",
          "sha1": "45b44ac019c69af34cbe811edae75ab81dbcf0bc",
          "md5": "dedb6104f0b2030dc6281a407ab3b159"
        }
      ]
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-jsir-0.8.28.klib",
          "url": "json-schema-serialization-js-0.8.28.klib",
          "size": 73626,
          "sha512": "8a59a89e81adb68845cfc194234b738323bd6072ace4b244e919f42cdaad5093ec4ea75bb36238e90117250eca296d9f177dba642c1f411d98a9b362087095f5",
          "sha256": "cdec176483f126ce26158cf130f7592d2b05e078bd6e33548d80fe19c93531bf",
          "sha1": "45b44ac019c69af34cbe811edae75ab81dbcf0bc",
          "md5": "dedb6104f0b2030dc6281a407ab3b159"
        }
      ]
    }
  ]
}
