{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.19/json-schema-serialization-0.8.19.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-macosx64-0.8.19.klib",
          "size": 73809,
          "sha512": "cd6ef631570c70d2db79afeaf5f6101eeb82905f2328bea8547b60566fa49b81ac875b73eafa0e9aa6670a509567f113bcff24f1b491c2fbfbf13b192cd316eb",
          "sha256": "13c4a697add5d62da858764433f8dec1a27c505a5ad4dad241ae749320709589",
          "sha1": "fe1e7c83134904346d71d50244f3e1e587da04a7",
          "md5": "1fb3629ab73220d0dba62cc7aa4765e3"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-macosx64-0.8.19-metadata.jar",
          "url": "json-schema-serialization-macosx64-0.8.19-metadata.jar",
          "size": 261,
          "sha512": "f41771b39451e69b4e6d0643cb6cc0e2fa219619a308c863b77a808efffa536c1f43df214f8f0a495e58a40e2fa35af0f6ed3d00ca740a0ff93d9ae8260e4544",
          "sha256": "62466c84113affe4dd80c8339547f85924e746a158aed64fcc36cb6f90507cd7",
          "sha1": "ceebafc2ec9a83d3b8dbd61d97de2f5993aaa701",
          "md5": "ce5ad7b0e9d3ad8e3389e4d703a2638f"
        }
      ]
    }
  ]
}
