{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.0/json-schema-serialization-0.8.0.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-iosarm64-0.8.0.klib",
          "size": 71042,
          "sha512": "cee54498ee1be3b05390696b90cbf71597b100862eaf8912c5b66890fb4d9a64867edf71128b1d9076f971c63ad43e1d9e0e8b8b16b0b1122ddf2104b1aa31dd",
          "sha256": "01e4675af0682b6821d29411e837628d619c1af4428b783ba08c2993bd3f13a8",
          "sha1": "6bf4d96259008f3adc5eeef2f92487c2b58a3c79",
          "md5": "7d48b7aa97e00e31a951f4699cb72adf"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-iosarm64-0.8.0-metadata.jar",
          "url": "json-schema-serialization-iosarm64-0.8.0-metadata.jar",
          "size": 261,
          "sha512": "813c60952dcd2a6d8b07478691753c77974e47ec39e99584b149dc4d962711bc4299a49f7136502d28b6da100f46e7b647db86e4c79084c3e46aeb03ae062eaf",
          "sha256": "68e1bb4bf118e593da8606ea496e051c5d732c1590cc81bd22e11b03e1495361",
          "sha1": "2891626fbd7f3bba6b6fc1469be732198b509139",
          "md5": "c8ef61d26718fed907e1f981867844ae"
        }
      ]
    }
  ]
}
