{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.21/json-schema-serialization-0.8.21.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-iosarm64-0.8.21.klib",
          "size": 74134,
          "sha512": "0d667122a1c37140a962a2df792f146637d077b6e2d09757c6249cd7f4491f44af54c102b5929a142cdc6f3d4c61fc9efd50a75ea93713cde0f5de76a6202bbb",
          "sha256": "24fa221d470ec1364f2e01f42c2ce4c4488b956992aad339762cbca85ea42fd5",
          "sha1": "174a5332ff1a1cb096707cb03fca71c18bc924da",
          "md5": "0de945d10deb338815d4afcaf874ce4d"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-iosarm64-0.8.21-metadata.jar",
          "url": "json-schema-serialization-iosarm64-0.8.21-metadata.jar",
          "size": 261,
          "sha512": "3111b05c35e43d1ecf518db7e2eb271c342f0df408a9e3c02d0f025ae8ce98bc34010134e050c44c96bdb4be45ac3cf67979c8af84e653408c6f66b4c7d263ae",
          "sha256": "7aceb67023720a538725b69eba1abc77bd35fc477c0cfb40366dd15d79dfba6b",
          "sha1": "444342f4653e09bf0017fc6de9d2674b17c14c9d",
          "md5": "63111cbc4adca1304e2d458875804fcd"
        }
      ]
    }
  ]
}
