{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.29/json-schema-serialization-0.8.29.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.29",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-mingwx64-0.8.29.klib",
          "size": 76201,
          "sha512": "5609c2eeafdaf9ed055d12a07c8a05ecf8e8fbaf73cfb9c313d82addb43670ad9df6e2385cfaa8010eb58d73e2d178697b4fdc0df5a79c547e904bb359fd8765",
          "sha256": "706345b0b4bd7bbf2578fe087c0e9c9a6d6ac1a141422cc13fb1d48eaa72eac4",
          "sha1": "8f42feb228bb6552489fe1f2e8403cca56e7b39b",
          "md5": "c95f07851904ba0b74d633aaa9657a21"
        }
      ]
    }
  ]
}
