{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.5/json-schema-serialization-0.8.5.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-jvm-0.8.5.jar",
          "url": "json-schema-serialization-jvm-0.8.5.jar",
          "size": 142778,
          "sha512": "fbca82fe9957d846ac7c577dbeb0de67e7494950a6b622aca8f8332a702a753007c629c6560b32c87f7404580a2903e1c8ad6875415ebf7b1b0cc94628621e60",
          "sha256": "3765cd3ea3d153c4ea17777aa1edc8eb22c29bc68d9737dafa534995a9f12a40",
          "sha1": "06e85ef30494327203c5db87e25012ffc70f87d4",
          "md5": "8bd682ac615f7d3f50abd377d7c12c35"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-jvm-0.8.5.jar",
          "url": "json-schema-serialization-jvm-0.8.5.jar",
          "size": 142778,
          "sha512": "fbca82fe9957d846ac7c577dbeb0de67e7494950a6b622aca8f8332a702a753007c629c6560b32c87f7404580a2903e1c8ad6875415ebf7b1b0cc94628621e60",
          "sha256": "3765cd3ea3d153c4ea17777aa1edc8eb22c29bc68d9737dafa534995a9f12a40",
          "sha1": "06e85ef30494327203c5db87e25012ffc70f87d4",
          "md5": "8bd682ac615f7d3f50abd377d7c12c35"
        }
      ]
    }
  ]
}
