{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.29/json-schema-serialization-0.8.29.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.29",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-linuxx64-0.8.29.klib",
          "size": 76201,
          "sha512": "2ff6a1a878cac895e20ac30ca3fb399198cf26ea0672de8cab598b396e00c734b94cc60c450f8fce64346ac7b1bbbeabd7d5a0bf4f80ab35ea15ad10f7541e6c",
          "sha256": "8713e3a591c4bfd7b2ee3da99cfc2c4a8dc591ccb8347cb03455a905d4fbe678",
          "sha1": "6b03295324e17253089964dff0249fc26a71c83a",
          "md5": "2f3d82422bd7e049f2bdd48d6ff6788a"
        }
      ]
    }
  ]
}
