{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.14/json-schema-serialization-0.8.14.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-mingwx64-0.8.14.klib",
          "size": 73885,
          "sha512": "7063c1b785c5283f48763d3a488dbee921b7938a89de9b1e4b9ecb884d5b2e43b21f481485a700b90175e3c7ededa5012cd0c3fe82ca4ec174238008b2705c26",
          "sha256": "fba174f7ac9f2399060353cbce90f59c16fd4bfec57a6a221d00ed233f735887",
          "sha1": "686009fa385139f94f7108c3b57e7b268c59a3a1",
          "md5": "870c3c980f7169efc4f329315e47d5f2"
        }
      ]
    }
  ]
}
