{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.9.4/json-schema-serialization-0.9.4.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.9.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-mingwx64-0.9.4.klib",
          "size": 85253,
          "sha512": "ed4eb50e81bf0caf752cfb0b3a66af97334a0ae9081660932e2ce6873f04f708f981f2de76f328d26751cd147843c8ec23f555bff8fc35f94af47cb19e490dbf",
          "sha256": "ff0b173ef24a4bed9d60894bd1071022b6feab9e955df7c1156a16d7ae88e4bf",
          "sha1": "4c1ce2214580c553445fb6e7f0f4fe86ee7d2735",
          "md5": "7b5d78192f44c1e43df1b207bf0a7a55"
        }
      ]
    }
  ]
}
