{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.9.1/json-schema-serialization-0.9.1.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-jvm-0.9.1.jar",
          "url": "json-schema-serialization-jvm-0.9.1.jar",
          "size": 168352,
          "sha512": "e7757319199dcc32c7d8c21e67db2eced22e3554cbe5d4de51de9a00e026d1b5656a8331fbefa31e99cbe36a6c633ef358213dab3934aaefad0bf70416e5d080",
          "sha256": "5dcd2835ef08ee4c17514b08a084a2a75f552758abba8f84c9dc507827aa27e7",
          "sha1": "0b954fc8a4b2bc80a9c76111c9523b5cbfa1bddf",
          "md5": "9fab448ba86a46548d541f7fc8cdc1b4"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-jvm-0.9.1.jar",
          "url": "json-schema-serialization-jvm-0.9.1.jar",
          "size": 168352,
          "sha512": "e7757319199dcc32c7d8c21e67db2eced22e3554cbe5d4de51de9a00e026d1b5656a8331fbefa31e99cbe36a6c633ef358213dab3934aaefad0bf70416e5d080",
          "sha256": "5dcd2835ef08ee4c17514b08a084a2a75f552758abba8f84c9dc507827aa27e7",
          "sha1": "0b954fc8a4b2bc80a9c76111c9523b5cbfa1bddf",
          "md5": "9fab448ba86a46548d541f7fc8cdc1b4"
        }
      ]
    }
  ]
}
