{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-metadata-0.8.16.jar",
          "url": "json-schema-serialization-0.8.16.jar",
          "size": 12039,
          "sha512": "c179ecad5d92063cb8914c885c545bf83caa09eb9bc5304933c752a73c32531104cc2d0a1c5a5a543ae85ab4db0c7ea345315bc02a0c77aff9d2cde49a3d3844",
          "sha256": "74ddffacea1b6ee08acf8c0f34b9330ae64598e956ede95dc3d4d38e55118304",
          "sha1": "3a4881a7aff0f29dbd45ad54aed95c404db35431",
          "md5": "1083fa9ec393898f9bb75dda73bae700"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../json-schema-serialization-android-debug/0.8.16/json-schema-serialization-android-debug-0.8.16.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-android-debug",
        "version": "0.8.16"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../json-schema-serialization-android-debug/0.8.16/json-schema-serialization-android-debug-0.8.16.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-android-debug",
        "version": "0.8.16"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../json-schema-serialization-android/0.8.16/json-schema-serialization-android-0.8.16.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-android",
        "version": "0.8.16"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../json-schema-serialization-android/0.8.16/json-schema-serialization-android-0.8.16.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-android",
        "version": "0.8.16"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../json-schema-serialization-iosarm64/0.8.16/json-schema-serialization-iosarm64-0.8.16.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-iosarm64",
        "version": "0.8.16"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../json-schema-serialization-iosarm64/0.8.16/json-schema-serialization-iosarm64-0.8.16.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-iosarm64",
        "version": "0.8.16"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../json-schema-serialization-iossimulatorarm64/0.8.16/json-schema-serialization-iossimulatorarm64-0.8.16.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-iossimulatorarm64",
        "version": "0.8.16"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../json-schema-serialization-iossimulatorarm64/0.8.16/json-schema-serialization-iossimulatorarm64-0.8.16.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-iossimulatorarm64",
        "version": "0.8.16"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../json-schema-serialization-iosx64/0.8.16/json-schema-serialization-iosx64-0.8.16.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-iosx64",
        "version": "0.8.16"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../json-schema-serialization-iosx64/0.8.16/json-schema-serialization-iosx64-0.8.16.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-iosx64",
        "version": "0.8.16"
      }
    },
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../json-schema-serialization-js/0.8.16/json-schema-serialization-js-0.8.16.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-js",
        "version": "0.8.16"
      }
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../json-schema-serialization-js/0.8.16/json-schema-serialization-js-0.8.16.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-js",
        "version": "0.8.16"
      }
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../json-schema-serialization-js/0.8.16/json-schema-serialization-js-0.8.16.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-js",
        "version": "0.8.16"
      }
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../json-schema-serialization-js/0.8.16/json-schema-serialization-js-0.8.16.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-js",
        "version": "0.8.16"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../json-schema-serialization-jvm/0.8.16/json-schema-serialization-jvm-0.8.16.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-jvm",
        "version": "0.8.16"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../json-schema-serialization-jvm/0.8.16/json-schema-serialization-jvm-0.8.16.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-jvm",
        "version": "0.8.16"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../json-schema-serialization-linuxx64/0.8.16/json-schema-serialization-linuxx64-0.8.16.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-linuxx64",
        "version": "0.8.16"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../json-schema-serialization-macosx64/0.8.16/json-schema-serialization-macosx64-0.8.16.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-macosx64",
        "version": "0.8.16"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../json-schema-serialization-macosx64/0.8.16/json-schema-serialization-macosx64-0.8.16.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-macosx64",
        "version": "0.8.16"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../json-schema-serialization-mingwx64/0.8.16/json-schema-serialization-mingwx64-0.8.16.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-mingwx64",
        "version": "0.8.16"
      }
    }
  ]
}
