{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.9.0/json-schema-serialization-0.9.0.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-mingwx64-0.9.0.klib",
          "size": 83846,
          "sha512": "9e973cc20aacba73cea264c4149dd8e8f87b2eb659acf5d25ecf584d43ef1f7f403ae191b93cab9cf27704f5b4104f29182f6267b709fc66b2612d75c927d7d3",
          "sha256": "72eea002348ee1688c249d8179cb33dd4713f94134680ddecee7c5813bbf404e",
          "sha1": "7309bcd8dc61acb4654df4377658ad3b4a9f3dc7",
          "md5": "fa3b04b9dbb23eac3b41a9faa3e85b46"
        }
      ]
    }
  ]
}
