{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.9/json-schema-serialization-0.8.9.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-mingwx64-0.8.9.klib",
          "size": 73437,
          "sha512": "b1d46af869703c84343d915bde849484405071d256236229438d252f00603988f92207c4e48d0083b3f35b13535a3f271efdbe6edd3a69bf7f8dd1bd68431740",
          "sha256": "479090bf20710aa1e165f427b6a5549ba752828d1525b9ebd41e0bc1b3290524",
          "sha1": "9fb96d0b45bd1091f5b58e34ad8daadc50fe40a3",
          "md5": "56d13ada7ddc3f984b5f83cd15149248"
        }
      ]
    }
  ]
}
