{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.9.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-metadata-0.9.7.jar",
          "url": "json-schema-serialization-0.9.7.jar",
          "size": 13521,
          "sha512": "7933d9ed4b152d4e733d33fb0262f0d0103d5c5a3fe571e9b45be0e64ccba1b432fb0346e04ab14aaa1657224629300f78a9ced8cdf578055bc21c3991795d91",
          "sha256": "8a887850f5e57db1af1afa37fc7e7472e79960a262708153eddc530c5d238deb",
          "sha1": "2e2c923ea8a70e648aa9460b59ed6467cfdc579b",
          "md5": "73f1b39c859887e7a5b8746c307d8479"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../json-schema-serialization-android-debug/0.9.7/json-schema-serialization-android-debug-0.9.7.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-android-debug",
        "version": "0.9.7"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../json-schema-serialization-android-debug/0.9.7/json-schema-serialization-android-debug-0.9.7.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-android-debug",
        "version": "0.9.7"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../json-schema-serialization-android/0.9.7/json-schema-serialization-android-0.9.7.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-android",
        "version": "0.9.7"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../json-schema-serialization-android/0.9.7/json-schema-serialization-android-0.9.7.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-android",
        "version": "0.9.7"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../json-schema-serialization-iosarm64/0.9.7/json-schema-serialization-iosarm64-0.9.7.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-iosarm64",
        "version": "0.9.7"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../json-schema-serialization-iosarm64/0.9.7/json-schema-serialization-iosarm64-0.9.7.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-iosarm64",
        "version": "0.9.7"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../json-schema-serialization-iossimulatorarm64/0.9.7/json-schema-serialization-iossimulatorarm64-0.9.7.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-iossimulatorarm64",
        "version": "0.9.7"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../json-schema-serialization-iossimulatorarm64/0.9.7/json-schema-serialization-iossimulatorarm64-0.9.7.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-iossimulatorarm64",
        "version": "0.9.7"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../json-schema-serialization-iosx64/0.9.7/json-schema-serialization-iosx64-0.9.7.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-iosx64",
        "version": "0.9.7"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../json-schema-serialization-iosx64/0.9.7/json-schema-serialization-iosx64-0.9.7.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-iosx64",
        "version": "0.9.7"
      }
    },
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../json-schema-serialization-js/0.9.7/json-schema-serialization-js-0.9.7.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-js",
        "version": "0.9.7"
      }
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../json-schema-serialization-js/0.9.7/json-schema-serialization-js-0.9.7.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-js",
        "version": "0.9.7"
      }
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../json-schema-serialization-js/0.9.7/json-schema-serialization-js-0.9.7.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-js",
        "version": "0.9.7"
      }
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../json-schema-serialization-js/0.9.7/json-schema-serialization-js-0.9.7.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-js",
        "version": "0.9.7"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../json-schema-serialization-jvm/0.9.7/json-schema-serialization-jvm-0.9.7.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-jvm",
        "version": "0.9.7"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../json-schema-serialization-jvm/0.9.7/json-schema-serialization-jvm-0.9.7.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-jvm",
        "version": "0.9.7"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../json-schema-serialization-linuxx64/0.9.7/json-schema-serialization-linuxx64-0.9.7.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-linuxx64",
        "version": "0.9.7"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../json-schema-serialization-macosx64/0.9.7/json-schema-serialization-macosx64-0.9.7.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-macosx64",
        "version": "0.9.7"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../json-schema-serialization-macosx64/0.9.7/json-schema-serialization-macosx64-0.9.7.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-macosx64",
        "version": "0.9.7"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../json-schema-serialization-mingwx64/0.9.7/json-schema-serialization-mingwx64-0.9.7.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-mingwx64",
        "version": "0.9.7"
      }
    }
  ]
}
