{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.9.1/json-schema-serialization-0.9.1.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-macosx64-0.9.1.klib",
          "size": 84804,
          "sha512": "4ea6e708f9db2a1eedade8fdfb957dd3cb3e75bd86080b6223940e0c898648bf3e0fdb5fdf8fe7c5b8eba8c173f01df900cceae8c52f8ccaba94cc0fcd644383",
          "sha256": "310971baf03841013a791498555ba0378ed6b1f185b1bcd0277d187ea14ce409",
          "sha1": "4da6750ef85e92eaa342c4bac8d269fbe3c31779",
          "md5": "1c7d206527807055212ff53b7020cfc7"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-macosx64-0.9.1-metadata.jar",
          "url": "json-schema-serialization-macosx64-0.9.1-metadata.jar",
          "size": 261,
          "sha512": "9a137bbfd1a1785e672e50762f5f6342f7106859f99140d950382fe657c543a5286f4a7440d90326cf24ba8671e8f12b0a150a65f32ccf242873374368c1917f",
          "sha256": "d71c93257c69af8f428e760d1e6878134cbdb7c292020d6bf442766efa4a915f",
          "sha1": "6b1c5cbdeda81120413cc15e1766dc6912711f24",
          "md5": "2442d5bf1bc2246b5ae266870783c371"
        }
      ]
    }
  ]
}
