{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.9.4/json-schema-serialization-0.9.4.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.9.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-jvm-0.9.4.jar",
          "url": "json-schema-serialization-jvm-0.9.4.jar",
          "size": 168483,
          "sha512": "f25c6fa673fb92ab5745d2225d8df9c87c042a1c82744b781def981bac1de7e514dbd076631ed3bbdd7fdfa7c04f30f75d8d86bd5dcc315c27b418f70992c097",
          "sha256": "5707f148e2d65ddec22c4a48407bcbe4b08feab37ad9728b03dc7bbc501a79b1",
          "sha1": "236545bafec7e8e25b4616e09cf2ad9ec7d7ea8d",
          "md5": "4fea92208b724f6d1eddf922ea1c17fa"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-jvm-0.9.4.jar",
          "url": "json-schema-serialization-jvm-0.9.4.jar",
          "size": 168483,
          "sha512": "f25c6fa673fb92ab5745d2225d8df9c87c042a1c82744b781def981bac1de7e514dbd076631ed3bbdd7fdfa7c04f30f75d8d86bd5dcc315c27b418f70992c097",
          "sha256": "5707f148e2d65ddec22c4a48407bcbe4b08feab37ad9728b03dc7bbc501a79b1",
          "sha1": "236545bafec7e8e25b4616e09cf2ad9ec7d7ea8d",
          "md5": "4fea92208b724f6d1eddf922ea1c17fa"
        }
      ]
    }
  ]
}
