{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.12/json-schema-serialization-0.8.12.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-iosarm64-0.8.12.klib",
          "size": 73715,
          "sha512": "4481a314ddf22d98582f8f0533ae9e48b9c78a2fd8201cf68515ac754b3f9307dde2ce0b056f084145223e4d3702629c5f377dde6355a637ff0c6b8ae8fdacbc",
          "sha256": "5c5a4b90c8abd85673b167b9af9bf3372f7b4ed4fb9ad8915148b3e701b12e56",
          "sha1": "99dd4dd3ce637abd62f9c9e7002be7373a686fe7",
          "md5": "f4524b53c70ec9f9a70a4693d8d6ddcf"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-iosarm64-0.8.12-metadata.jar",
          "url": "json-schema-serialization-iosarm64-0.8.12-metadata.jar",
          "size": 261,
          "sha512": "166cbe6bfd82733d83b353e942bc931b2291929d2505598e3ef88da2d9fc5b4e1d88a0477fc369a56218e77a0549b75602ff46cf22f238460142c9ff383c6342",
          "sha256": "f84c20e44fb0bd73b9a1365f92ce6ebfde1d24af9b31cba6b5ad80c50a4f6a2a",
          "sha1": "5b7f8ee0d66c948592a25e2c18c644d341e6c810",
          "md5": "8e47678548256590d33325d6a4102d1d"
        }
      ]
    }
  ]
}
