{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.16/json-schema-serialization-0.8.16.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-mingwx64-0.8.16.klib",
          "size": 73703,
          "sha512": "c2eea62d210d89cf1dbebf30c6c45f281f5ac945dec06434a2a0993171337f7d9b4a632e691392ef8a0d8e6178e07ae6674e59fec3a3ecdbc8db21f63f87babc",
          "sha256": "dfc07b4579c66a83d1ae255cb86239c8133b279d0a25ae5d4de6d9a1c2105edf",
          "sha1": "0cec85fefbf5ab5a05e5cb51fa534913346ad439",
          "md5": "206f3e7c018997b2a728b2be52d5b500"
        }
      ]
    }
  ]
}
