{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.28/json-schema-serialization-0.8.28.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.28",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-mingwx64-0.8.28.klib",
          "size": 76144,
          "sha512": "73e327c68df75ceaedc90358595c2f5bcca417b3223fb40ca57af24df85decc78f15157876cc164fb3c060b7c66f649550b649379acd81977922cc60fcf0e2b0",
          "sha256": "dcddf8288059a493cb241c686dd5f45d9bce6bad69672d7d1f2a064d2a39b80e",
          "sha1": "329f9f1d7721ea9d6c6c07e2c12f22d37f5d3187",
          "md5": "691fc62c23de4456bd9b69d8caee543a"
        }
      ]
    }
  ]
}
