{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.8/json-schema-serialization-0.8.8.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-jslegacy-0.8.8.jar",
          "url": "json-schema-serialization-js-0.8.8.jar",
          "size": 36253,
          "sha512": "a2593f38da2df5628cb928b24568cd1486afbdf67dd6b9d31b6df342de6ba24bdb29f6720a1f32e768888a8cafa0a9b80e0c27fb789157c237a67ddcb0f6f198",
          "sha256": "b55010697653d9dfa3f461fc875051f19772da170d18b16383ab8e35a390412e",
          "sha1": "9bae46ef095a8d03eb6a7daa715bc7f0729d310c",
          "md5": "694ecf12cb6628855d2b09a363536990"
        }
      ]
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-jslegacy-0.8.8.jar",
          "url": "json-schema-serialization-js-0.8.8.jar",
          "size": 36253,
          "sha512": "a2593f38da2df5628cb928b24568cd1486afbdf67dd6b9d31b6df342de6ba24bdb29f6720a1f32e768888a8cafa0a9b80e0c27fb789157c237a67ddcb0f6f198",
          "sha256": "b55010697653d9dfa3f461fc875051f19772da170d18b16383ab8e35a390412e",
          "sha1": "9bae46ef095a8d03eb6a7daa715bc7f0729d310c",
          "md5": "694ecf12cb6628855d2b09a363536990"
        }
      ]
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-jsir-0.8.8.klib",
          "url": "json-schema-serialization-js-0.8.8.klib",
          "size": 70899,
          "sha512": "20aadcba869d555e49d185617937ac4b1256e168690149bae180397247ec5e1b2b254afd87079c5b5f517f0289eae084b5fd8dfb94979dec800a155b627c7f5c",
          "sha256": "0ef815d1deb97f67855497fda38f7c99f584ab5f07a3f1ba490aa8f344253036",
          "sha1": "573c93ff9a1acbbc297cef69cd84e961d87e435b",
          "md5": "01fb9d55cbb869afa6bcb4fa57c8129c"
        }
      ]
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-jsir-0.8.8.klib",
          "url": "json-schema-serialization-js-0.8.8.klib",
          "size": 70899,
          "sha512": "20aadcba869d555e49d185617937ac4b1256e168690149bae180397247ec5e1b2b254afd87079c5b5f517f0289eae084b5fd8dfb94979dec800a155b627c7f5c",
          "sha256": "0ef815d1deb97f67855497fda38f7c99f584ab5f07a3f1ba490aa8f344253036",
          "sha1": "573c93ff9a1acbbc297cef69cd84e961d87e435b",
          "md5": "01fb9d55cbb869afa6bcb4fa57c8129c"
        }
      ]
    }
  ]
}
