{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.5/json-schema-serialization-0.8.5.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-iosx64-0.8.5.klib",
          "size": 71335,
          "sha512": "b2f7725144b0ca1fb175a3236980c10a0a16e1d775fe367b7041fef4c0bef471eca199fab21d371e1830fc7817c348411fae81e4ca5b6d19c3002b1f9edfa200",
          "sha256": "ebfe783f7b01ddf8b227405ab6976227f9030a848b4c9eb200bc4b78ece18d44",
          "sha1": "eb70cf8d294b2138c9bdc233343c3163e533051c",
          "md5": "66ee54b4adba043ea2cf30aa2e8f0135"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-iosx64-0.8.5-metadata.jar",
          "url": "json-schema-serialization-iosx64-0.8.5-metadata.jar",
          "size": 261,
          "sha512": "987b04ed922cfdc4ac2e9a39246c4a9ed6449950ca944dc83999d32146ca0b5ba64c2fd7b40c9d0e88acfe8b39c39aa833e09c4cbdf8f2451ee606fb8b70a674",
          "sha256": "4049f0615f2bd4528644bae064afe704bd34291775afbd07a77c216a7ddb25ba",
          "sha1": "433fb7888002a8cfa8ce6417579fc81444232013",
          "md5": "2005c143e52876c0ae374bf06e1cde13"
        }
      ]
    }
  ]
}
