{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-metadata-0.8.0.jar",
          "url": "json-schema-serialization-0.8.0.jar",
          "size": 12156,
          "sha512": "6cc2b46cb8af4208eacc71fda65adbe605b2b9d7d3b4255d0029d51f9eb5cc525a35de8bb943e5b1d34e3c2034a18291c05b1ff48f2624f0f99a134811df3914",
          "sha256": "60b9296b516887650b86cacc7c19ba61921f7dd63d2dd6849155d347059bae6e",
          "sha1": "02d8cd6537984bae2cfc1ea236de388448982a29",
          "md5": "96911dc78a5185cfeb0291577a674ca5"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../json-schema-serialization-iosarm64/0.8.0/json-schema-serialization-iosarm64-0.8.0.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-iosarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../json-schema-serialization-iosarm64/0.8.0/json-schema-serialization-iosarm64-0.8.0.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-iosarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../json-schema-serialization-iosx64/0.8.0/json-schema-serialization-iosx64-0.8.0.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-iosx64",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../json-schema-serialization-iosx64/0.8.0/json-schema-serialization-iosx64-0.8.0.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-iosx64",
        "version": "0.8.0"
      }
    },
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../json-schema-serialization-js/0.8.0/json-schema-serialization-js-0.8.0.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-js",
        "version": "0.8.0"
      }
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../json-schema-serialization-js/0.8.0/json-schema-serialization-js-0.8.0.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-js",
        "version": "0.8.0"
      }
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../json-schema-serialization-js/0.8.0/json-schema-serialization-js-0.8.0.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-js",
        "version": "0.8.0"
      }
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../json-schema-serialization-js/0.8.0/json-schema-serialization-js-0.8.0.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-js",
        "version": "0.8.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../json-schema-serialization-jvm/0.8.0/json-schema-serialization-jvm-0.8.0.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-jvm",
        "version": "0.8.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../json-schema-serialization-jvm/0.8.0/json-schema-serialization-jvm-0.8.0.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-jvm",
        "version": "0.8.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../json-schema-serialization-linuxx64/0.8.0/json-schema-serialization-linuxx64-0.8.0.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-linuxx64",
        "version": "0.8.0"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../json-schema-serialization-macosx64/0.8.0/json-schema-serialization-macosx64-0.8.0.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-macosx64",
        "version": "0.8.0"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../json-schema-serialization-macosx64/0.8.0/json-schema-serialization-macosx64-0.8.0.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-macosx64",
        "version": "0.8.0"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../json-schema-serialization-mingwx64/0.8.0/json-schema-serialization-mingwx64-0.8.0.module",
        "group": "com.github.Ricky12Awesome",
        "module": "json-schema-serialization-mingwx64",
        "version": "0.8.0"
      }
    }
  ]
}
