{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.9.4/json-schema-serialization-0.9.4.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.9.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-iosx64-0.9.4.klib",
          "size": 85235,
          "sha512": "36153277b4a30d68eb775ad63ababf8f9141ed16389cbd7a19d6b34bb3a2f4b2f37e84e5e4fbf0cb44598d9ac313118e97acd43020ecd9e68e5094174b9b9f44",
          "sha256": "88490e7d21b2a045c46dea3fa297ee8237df0a2840c9c337439402aaf9364922",
          "sha1": "2ce3a764c90d2f57f77892b8121e531040ffd753",
          "md5": "53c449ab5696255418fe231adda8295d"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-iosx64-0.9.4-metadata.jar",
          "url": "json-schema-serialization-iosx64-0.9.4-metadata.jar",
          "size": 261,
          "sha512": "ae7adbe2d55a0b2161157cf307f41c0799679b3c0f7efa13e6b03762032ae370516098c7e899d0d5734a987a6cc0baec914378e68f991954b14e26cd7a437ce4",
          "sha256": "54360ee012a8abf22cb91893541b611a151464fd4cda47e44ceeb926bc33bbac",
          "sha1": "a32d548ec160db828db156ffc6acf5500d58ecf8",
          "md5": "a6a524c44f91ed335e6ed3a6ebe9a250"
        }
      ]
    }
  ]
}
