{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.7/json-schema-serialization-0.8.7.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-mingwx64-0.8.7.klib",
          "size": 73378,
          "sha512": "3862a3f39ac97acef5aea4a0121b4b75be776e6534fa27dbc5aa3c432d7c79230b81e51494ad92ca7e6edb58751aaa02771b8264d41de0e20ff08032fe28562f",
          "sha256": "bf99f394a07633ce240e3db969a3218599c6a60d0a2569d27599900987c0d669",
          "sha1": "1d443ced62973cbd325c3ed730d9ddbeddcfa143",
          "md5": "e4dc72c7845d4842737711dce7081af6"
        }
      ]
    }
  ]
}
