{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.2/json-schema-serialization-0.8.2.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-iossimulatorarm64-0.8.2.klib",
          "size": 70876,
          "sha512": "e22d459055bb756979788ef1862017e7ef38a7ef55027d1a7addf779dcd073d354352acec7284f08d36a15336269d4a41be760b992ac398b31a18446e0415ed5",
          "sha256": "c0dadc414db49c5f0f058c36281c434afc5d1d5e0fc3f230b9320c99bf09d02c",
          "sha1": "1a5bb8265c917e107b2b6e022aeef289b62b3799",
          "md5": "7a48b6d5b91e1bef03e3f09ccc854fc1"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-iossimulatorarm64-0.8.2-metadata.jar",
          "url": "json-schema-serialization-iossimulatorarm64-0.8.2-metadata.jar",
          "size": 261,
          "sha512": "0513a8f1c3fae875cf9a813c1037ea3048dc66ce9d18dacabf35ee05125fd164860836af22b971291fc3e8eea55f29c29244a5f2d9a0e98ee992b0a206b5a3af",
          "sha256": "76f12892d232ff6dd59be1d357addeda9f44e422487241d04a8d90f4c91ac444",
          "sha1": "95f31cccc8091ce73be53f9336d2dedb7aca1231",
          "md5": "630d4dbc699a1ebc2cb6c2884b156ba0"
        }
      ]
    }
  ]
}
