{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.8/json-schema-serialization-0.8.8.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-iosx64-0.8.8.klib",
          "size": 73383,
          "sha512": "93908cbf7036a19ef738860fbaeea8bebf9315aceed66de1ba57f955ea458fa563ba0c49bc2a7c5dd8dba8c334e1df786c8101033cf8d33d072ee422975f0a98",
          "sha256": "c19d6a64a4f749fba20b386fcdc1fd123328dfc5b25da2864249759b8b6b35a3",
          "sha1": "855b1fe274aef9cc75968625d9ebf432f58c15ba",
          "md5": "7b86b7adaf4f3003b45383a66366a7d6"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-iosx64-0.8.8-metadata.jar",
          "url": "json-schema-serialization-iosx64-0.8.8-metadata.jar",
          "size": 261,
          "sha512": "685deb0650fbd0ac347f392828861a045ead40a8fe2c6ac472bfe71b4f80bcaf5f2291cbd56ace05a7dd34705e62d4e3161cf7c88afea943f4df1ff146e905a3",
          "sha256": "da842bf0a138484f7435315701beacd046dd5e48e0b9504bfcad3836be6daa5e",
          "sha1": "bd4da948cbdfb54d46d43c0aa65afc7b20b16b89",
          "md5": "42a43206700151cf8398eb3ec6fe5231"
        }
      ]
    }
  ]
}
