{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.0/json-schema-serialization-0.8.0.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-iosx64-0.8.0.klib",
          "size": 71025,
          "sha512": "a0f7754896bd5ac83b3a4c96fc1e0ce9ca74ee90f19ac06170922c75978da0d7065624bf7e2d98d8f9a59beffa7d79f9fd0054c56b752ed5636333f290f08f8c",
          "sha256": "aa7f11057560b03ed06ce3c012d74a864bf29924b892829a258ceb7ce0f53bd9",
          "sha1": "0a2e01ed11aa7bc1acc32bb5af90321d69439630",
          "md5": "a389884e3a771dbf743d1297d17f6257"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-iosx64-0.8.0-metadata.jar",
          "url": "json-schema-serialization-iosx64-0.8.0-metadata.jar",
          "size": 261,
          "sha512": "813c60952dcd2a6d8b07478691753c77974e47ec39e99584b149dc4d962711bc4299a49f7136502d28b6da100f46e7b647db86e4c79084c3e46aeb03ae062eaf",
          "sha256": "68e1bb4bf118e593da8606ea496e051c5d732c1590cc81bd22e11b03e1495361",
          "sha1": "2891626fbd7f3bba6b6fc1469be732198b509139",
          "md5": "c8ef61d26718fed907e1f981867844ae"
        }
      ]
    }
  ]
}
