{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.9.1/json-schema-serialization-0.9.1.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-iosarm64-0.9.1.klib",
          "size": 84928,
          "sha512": "3e2c2603f30d4b6bca3af3419f9a3f98e781f0f52549c54d4743cd7e7cf3659e4a15e1494e04bccc477e3ca64006e4927f70596dbd34577230e5d5bf5ca2100f",
          "sha256": "a7f279fc6ce469fde07bf663e01bfa2873fe941169e76d001141f437b6e6bed6",
          "sha1": "9dbb1a8b561b3f0bebcfdcc0edde274881bc2972",
          "md5": "4c9a1ec1c9ca5a06b780d6cb29627782"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-iosarm64-0.9.1-metadata.jar",
          "url": "json-schema-serialization-iosarm64-0.9.1-metadata.jar",
          "size": 261,
          "sha512": "d7570ee2640b4aec1860f53b22bfc147d7a1b498f58ed4883e4ac498a6ab0d7d248e4b7bee088a0eb858c79cb4cf9b584a5ab3726a6ac061c09ad138e297fcc5",
          "sha256": "0e379c511f41ca46149ec1fea7df6e7f62759ae1798fdbb869eddcd7a591194e",
          "sha1": "301112861e569560c5ba8a5729ecab09065a9c80",
          "md5": "3c46a0612f249928da28d906c8effdc6"
        }
      ]
    }
  ]
}
