{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.9.1/json-schema-serialization-0.9.1.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-iosarm64-0.9.1.klib",
          "size": 84803,
          "sha512": "c42026f5fc2da9062a26783414b62d27046e89b87abbbfecb2faae6ce3151c5a957f22a664322991062a89297908d3e4cab53122745be4d9cdf7432df0cca066",
          "sha256": "a95dd24d0ea2db7522a1ba0ae6c1d10dd43da7fd72b76f99169d1a40e12d8b49",
          "sha1": "fc97b3b73ca5e98721672aec779eb7d0cad13a0b",
          "md5": "43c1a035efad53d2429c5cd7c1f19929"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-iosarm64-0.9.1-metadata.jar",
          "url": "json-schema-serialization-iosarm64-0.9.1-metadata.jar",
          "size": 261,
          "sha512": "d7570ee2640b4aec1860f53b22bfc147d7a1b498f58ed4883e4ac498a6ab0d7d248e4b7bee088a0eb858c79cb4cf9b584a5ab3726a6ac061c09ad138e297fcc5",
          "sha256": "0e379c511f41ca46149ec1fea7df6e7f62759ae1798fdbb869eddcd7a591194e",
          "sha1": "301112861e569560c5ba8a5729ecab09065a9c80",
          "md5": "3c46a0612f249928da28d906c8effdc6"
        }
      ]
    }
  ]
}
