{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.19/json-schema-serialization-0.8.19.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-iossimulatorarm64-0.8.19.klib",
          "size": 73895,
          "sha512": "5d40880c04d2ba16f6e01824a35a9078c82d39f6d84aab7cf44e50d106667f4387921eb85d72398d97da8e7a8809f67d02ff0d691d5c3c62666ca30748f414df",
          "sha256": "30e7b72a6e3f94348255239bb6a20a7a93a8cb96e9ca350ffa2b03ffafceeeff",
          "sha1": "7e8a37b3b84342357f38cab164bc1adcf0cdcff4",
          "md5": "db94204ce188274e50c74478a22363e8"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-iossimulatorarm64-0.8.19-metadata.jar",
          "url": "json-schema-serialization-iossimulatorarm64-0.8.19-metadata.jar",
          "size": 261,
          "sha512": "6eafcd1c8f88d21ef0018c2ca616104b4911b8e4e9d22290a9e6f89f716faaed988eb4d714d20f2a39a5b1c95d9b7a0b94dda582364cbdfeb2efbfe5e413b281",
          "sha256": "2dbaad8905b6de113833218d633d017924622798c5a1dbe32845118118789569",
          "sha1": "b97b8eba2b04e2d60d7a298db8e13b6edc5cf43d",
          "md5": "34664b769191d93c18b6b0e97f73aa6b"
        }
      ]
    }
  ]
}
