{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.9.6/json-schema-serialization-0.9.6.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.9.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-iosx64-0.9.6.klib",
          "size": 85242,
          "sha512": "df37d2a8717eb363bd8fc0e037ed2484f63cdde0ce3d4e11af2213ee0e068772db88853a15faf224e9636a7c0004e535dbd56f32d10de54fa74ac1643df75603",
          "sha256": "6490730f76b745c50f20f565749e5e3bb4d4c79c740b819e9c15187e384b8460",
          "sha1": "0dd2586f1b1953bfdb7a5879ce940b34f6c08e3c",
          "md5": "6378199a38d63d312558caf7b1c2bec6"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-iosx64-0.9.6-metadata.jar",
          "url": "json-schema-serialization-iosx64-0.9.6-metadata.jar",
          "size": 261,
          "sha512": "ee24cd17614e19a0bce44693f07ea716c893ddc5e178758b775cbc9022717de3f3c3f6a47471aef68bb4bc58b9677f3ac3a5fc63df546b5dde3d06f6544683df",
          "sha256": "415670524070dc8528d3784709794523d2d00dccc259b1496a2b9404acce1cdf",
          "sha1": "46ad5a900760fe29951c38ffeda21ebd9df72f25",
          "md5": "896ca09bf9701f074b4cab049ec85d2f"
        }
      ]
    }
  ]
}
