{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.9.1/json-schema-serialization-0.9.1.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-jslegacy-0.9.1.jar",
          "url": "json-schema-serialization-js-0.9.1.jar",
          "size": 58462,
          "sha512": "0ce2819733d828e375abf8558e5f518edfe0987baf9b6b8e972c25e58d5a1e068f0f5e39cf355455001e5691681a0a60489919eeef18a9ba86852e831dd77f17",
          "sha256": "6aa3c881ff4c0898f154dc83dd34ad4ce8d20464ac3eab11011b470016220076",
          "sha1": "521feefc4724fa537c7a305ac1704de3d81cff03",
          "md5": "707d27cb47b2ec0c1080dce96edfe302"
        }
      ]
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-jslegacy-0.9.1.jar",
          "url": "json-schema-serialization-js-0.9.1.jar",
          "size": 58462,
          "sha512": "0ce2819733d828e375abf8558e5f518edfe0987baf9b6b8e972c25e58d5a1e068f0f5e39cf355455001e5691681a0a60489919eeef18a9ba86852e831dd77f17",
          "sha256": "6aa3c881ff4c0898f154dc83dd34ad4ce8d20464ac3eab11011b470016220076",
          "sha1": "521feefc4724fa537c7a305ac1704de3d81cff03",
          "md5": "707d27cb47b2ec0c1080dce96edfe302"
        }
      ]
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-jsir-0.9.1.klib",
          "url": "json-schema-serialization-js-0.9.1.klib",
          "size": 83716,
          "sha512": "6d6c8a8a97f268fb1841311f0ee9d3372e1d2e2a67e0190901542cb6c76a0f2c5bc0d9f1b22ca74a132f99e4f59f271a3bc98c29209021843f968eb035287cd7",
          "sha256": "d9041f4565cc27386d1be5e17af554f266a4120de9aa8b2de8f39e4eae714b0e",
          "sha1": "4a66005992bdae1cf00d46fe3aa11ee22a76d8ef",
          "md5": "1ec35eac4777da3936b6953e2f5bb94d"
        }
      ]
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-jsir-0.9.1.klib",
          "url": "json-schema-serialization-js-0.9.1.klib",
          "size": 83716,
          "sha512": "6d6c8a8a97f268fb1841311f0ee9d3372e1d2e2a67e0190901542cb6c76a0f2c5bc0d9f1b22ca74a132f99e4f59f271a3bc98c29209021843f968eb035287cd7",
          "sha256": "d9041f4565cc27386d1be5e17af554f266a4120de9aa8b2de8f39e4eae714b0e",
          "sha1": "4a66005992bdae1cf00d46fe3aa11ee22a76d8ef",
          "md5": "1ec35eac4777da3936b6953e2f5bb94d"
        }
      ]
    }
  ]
}
