{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.24/json-schema-serialization-0.8.24.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-mingwx64-0.8.24.klib",
          "size": 74357,
          "sha512": "56a94678baccfa05f53f71d1ae30bf8417a0cc9f5388e086a92a91b5b26ceca801ba8675ba6984eb7ad2cb3ed6f3bea4c8fd239a09d212bdee2523c4cdf386f2",
          "sha256": "aaee066d73955d69d5513cee6db5cec70c1164e4a0c9040f2252e203b1ed8b7b",
          "sha1": "b8b0f3ced4cb0ff02e4aa5c95f846c9b8819dd75",
          "md5": "4534c6c81a78408d443aaf5883a9d49b"
        }
      ]
    }
  ]
}
