{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.9.3/json-schema-serialization-0.9.3.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.9.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-mingwx64-0.9.3.klib",
          "size": 85194,
          "sha512": "1428d32d93a2b6b6b8d25c5f3bacd760481461db463a9a5c3c7fdd4eb305cdbf5efaa85b6e40f37c574db6bb7dd5502a3423c2902c922082ab9d206acbff19a7",
          "sha256": "facc578d247661d9ff5cf2ccf64e84813a0cb13b029368120fe5ab26ab99af6d",
          "sha1": "d9dca928ad24799901b1ae2d1865defe84d5f992",
          "md5": "42398f365597c6375cca8ddbbcc5453b"
        }
      ]
    }
  ]
}
