{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.27/json-schema-serialization-0.8.27.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-macosx64-0.8.27.klib",
          "size": 76307,
          "sha512": "f077b5fcba5ce62837f04ae594e0b6b36481c86e0ed83945bcbf8a9c445bc7f39bbc029d3961913a6ac9454950da3d6d99784c5febb60f99ac348e41149e660d",
          "sha256": "c78d599bf9e89bdc7b91befb3bb9bd1023737369a73ed89edb95e310dd3e16b6",
          "sha1": "f001b9b065c3847aa9dc2d943be124fdbf987508",
          "md5": "fcfb3a83830a2a10ce093fa9a32a8fb1"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-macosx64-0.8.27-metadata.jar",
          "url": "json-schema-serialization-macosx64-0.8.27-metadata.jar",
          "size": 261,
          "sha512": "8a8abfdeb6a79aa4dd9b0c8bada332fed9f3c0801fb33ed4c02bc625212c6e6cae49e2e2ae15e5656d4936ee43cd9a7e0f0afa56bf8270ad86df2200c012a81f",
          "sha256": "09adcddf61d2788a1d9f7794a86f28637cdb3b7e1a7956cd1002c2d618201975",
          "sha1": "46269a4746e09ad24c57cd28000ad041fa3278c6",
          "md5": "35a777febac0d4e3b180c28535301463"
        }
      ]
    }
  ]
}
