{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.19/json-schema-serialization-0.8.19.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-linuxx64-0.8.19.klib",
          "size": 73809,
          "sha512": "02513e0e9220f125888efe4b425ab2942cf284bdde1ffc54f338249aebefa687416495f0bd5bf0781a488667cd34a54fb92ea0edaa4068dfbedf24ebf37ce50e",
          "sha256": "e8a0d6d6c63fb833c12517d4665bf74bdc1d547c6829e4b4091a776702685252",
          "sha1": "fa7a86a1a47a1ccb67076e9edbb1cb8118a91733",
          "md5": "3ef3771417a51bfcc67d3a20dbd99ea4"
        }
      ]
    }
  ]
}
