{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.15/json-schema-serialization-0.8.15.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-mingwx64-0.8.15.klib",
          "size": 73654,
          "sha512": "a1d23bdcadb8537af68ccf50d28531f7b4772c5bbe5ba0b3291fdbb17909c6806e7753f8a1573f233dbc7fc8a1c72955d92ee785dbf6c94693bb2e330c98a4a7",
          "sha256": "f1779d1b9d14ecbe99abfadbcae443bef879f5b07f3318240b89fb625e9363ec",
          "sha1": "8bceb9a1638c19fb8842042b9377169cd1ae5473",
          "md5": "81a16fdc99c20c637761243e4b7aaa73"
        }
      ]
    }
  ]
}
