{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.4/json-schema-serialization-0.8.4.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-debug.aar",
          "url": "json-schema-serialization-android-debug-0.8.4.aar",
          "size": 133741,
          "sha512": "a6a00688d66c0462a76e6dc4ec598e14a8db3dc10fd3f00a119a06983dd4f26db4c5686f4ca508cbb6eaddf913699885661611c5f60b20931c7dc4df5ff0f669",
          "sha256": "6085616be771e9790eaaf092a5b505a29512f7de36bd83fe09ee111f5147463d",
          "sha1": "7dff6dbb74e58b37deaea821d8f95dd35d902c69",
          "md5": "cfa0f1848209d3a4ca5134042fc9b8c1"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-debug.aar",
          "url": "json-schema-serialization-android-debug-0.8.4.aar",
          "size": 133741,
          "sha512": "a6a00688d66c0462a76e6dc4ec598e14a8db3dc10fd3f00a119a06983dd4f26db4c5686f4ca508cbb6eaddf913699885661611c5f60b20931c7dc4df5ff0f669",
          "sha256": "6085616be771e9790eaaf092a5b505a29512f7de36bd83fe09ee111f5147463d",
          "sha1": "7dff6dbb74e58b37deaea821d8f95dd35d902c69",
          "md5": "cfa0f1848209d3a4ca5134042fc9b8c1"
        }
      ]
    }
  ]
}
