{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.12/json-schema-serialization-0.8.12.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-release.aar",
          "url": "json-schema-serialization-android-0.8.12.aar",
          "size": 129236,
          "sha512": "15a27a60f725a24178c50547c9bb1fbe15f6de77c44b2baa12173379352f772e19a58650e1a6bf2c1e7d2f28d1dd0544b9f640730da355c50f4407f5219f809c",
          "sha256": "cf30267ec4c364fd18e3063733afa707f8e44dcf84539aa0698a2e010cb568e4",
          "sha1": "83d154f48788fd4945cdb23e0114bedbb6e7c19e",
          "md5": "18c4c09b00f2bd0e9b0c7d1c08d8ab4d"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-release.aar",
          "url": "json-schema-serialization-android-0.8.12.aar",
          "size": 129236,
          "sha512": "15a27a60f725a24178c50547c9bb1fbe15f6de77c44b2baa12173379352f772e19a58650e1a6bf2c1e7d2f28d1dd0544b9f640730da355c50f4407f5219f809c",
          "sha256": "cf30267ec4c364fd18e3063733afa707f8e44dcf84539aa0698a2e010cb568e4",
          "sha1": "83d154f48788fd4945cdb23e0114bedbb6e7c19e",
          "md5": "18c4c09b00f2bd0e9b0c7d1c08d8ab4d"
        }
      ]
    }
  ]
}
