{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.1/json-schema-serialization-0.8.1.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-iosarm64-0.8.1.klib",
          "size": 70329,
          "sha512": "fa4e7fe2f93edb0b748118b853aa9ce4fa6bb39ad577c6569f44a4cb8664345816215b30e9218cbcdcfac5477992d9dd07520908a95b1f1fae871d245365cea5",
          "sha256": "07f050ad17b1f8a742ca995eed298dac0ac634335a09cf8f821866a256dcad93",
          "sha1": "e5248b8f86541c205ddc4675538aaea516dee91e",
          "md5": "4083e9fd0d1401044904a07bea1bb585"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-iosarm64-0.8.1-metadata.jar",
          "url": "json-schema-serialization-iosarm64-0.8.1-metadata.jar",
          "size": 261,
          "sha512": "afe1c8ed703d5861790729710fe73b2ffbf174e870efe9f51d226d3d758eac6b78290c1b1f36bfc3318b6304630382deb4de1e0e4d96686e2208f0169b123b96",
          "sha256": "2cd1664f066bb5afae67da268c55408e4486bc5c69a13a7c9e0827dffb0c78ea",
          "sha1": "b0cda044df3d1268c7eb36702cb17da812a4e8d0",
          "md5": "ba38e52afb9ef2e2f9fe136dc822dd0a"
        }
      ]
    }
  ]
}
