{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.8/json-schema-serialization-0.8.8.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-linuxx64-0.8.8.klib",
          "size": 73401,
          "sha512": "1ac42363d0f6ee358e88a5b976df172dc1af9b35a24da51bbc2005a4a7d66202cae7eb2c55148117c78f39cfc4670e4bc28bb7a7e12809c9fd0ffc39545dd21b",
          "sha256": "09b6c494eeb3719e18e7de0fcea3927cd0d387274adfc00a4d7165174d82d6d2",
          "sha1": "4645403e7d77eff68e6ed8838e06cbf33d774e69",
          "md5": "bc380edf263730b4acff7a44cfe4debe"
        }
      ]
    }
  ]
}
