{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.9.8/json-schema-serialization-0.9.8.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.9.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-linuxx64-0.9.8.klib",
          "size": 86004,
          "sha512": "df304b191a3049c94b1c3f5dcabe4d05c0b4859a5becaf665e6df87340a874836d75ebcc4302783224ce82a4c3fea09320a42e432c206d49e1e46a61c860aa63",
          "sha256": "71a94f7047c8753195701cc6d8834255a17c15ff39747b26157559452c6841db",
          "sha1": "75a4d1270a02e2aa9d44e33c5cc01703d6cea4fb",
          "md5": "27a52155d5b1dce3ffd97d595b468cfd"
        }
      ]
    }
  ]
}
