{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.1/json-schema-serialization-0.8.1.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-linuxx64-0.8.1.klib",
          "size": 70330,
          "sha512": "f9a2150752ada868f8813df1c033bfddd9e3189ca0fd9a606efe140611098b34b2b988d5eec5899a9ad76d90d2c79ae17e1988afda748193c5ee4eb4ac5839d9",
          "sha256": "877e36a7773fcf13867dc9172a0cdefdeb8c03c382cd3f65ac58554fa5931162",
          "sha1": "3a0f9110e0b6370b541ddee2f6500fc826ba3e21",
          "md5": "84d7b3455b8538b9fdf7bb3f9feacc0c"
        }
      ]
    }
  ]
}
