{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.9.3/json-schema-serialization-0.9.3.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.9.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-linuxx64-0.9.3.klib",
          "size": 85194,
          "sha512": "3febb9c3edc29a14e6a8df1ff8fe40becb6cb005bef27ff3cc3a7ff5b9f2436f728d59ba29f92733b66f5025537c4e4f4692850c8ffd688109f04a071e40d0ef",
          "sha256": "e670cdd3e26b10c9a17fd42f31600de7d6bafbbd7d6560cb51f1ab96c7b984d8",
          "sha1": "2fab00da82de26dfa90e0cc2b7be70854d0e28e0",
          "md5": "efc4b4e8578a11dd3514980e18ad92bd"
        }
      ]
    }
  ]
}
