{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.3/json-schema-serialization-0.8.3.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-macosx64-0.8.3.klib",
          "size": 71004,
          "sha512": "732a9ac60e9fa453f06a6265d56b66ce71b322f994b1abc4902263934201c3078bd984b3cb509f60ca66cc123101cc3ac72a50b23bf309837b6161a7b784902d",
          "sha256": "b1ea86222f51ca8574aef2d87d674ab5cbb433b1b340d1d0a042b785e2d97a3a",
          "sha1": "04d72e67fb593d8ee6acf6c6c712be5b1af7a8f2",
          "md5": "f67cb94b6ab3adc1c41c9fb59f319b0b"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-macosx64-0.8.3-metadata.jar",
          "url": "json-schema-serialization-macosx64-0.8.3-metadata.jar",
          "size": 261,
          "sha512": "00d2ae832bf3358ae812ba23a15e6cf934003b477e713482305e8b817bd27340c5c776c27f0659b76b2449f6ae52d1bbe245c8cda9eb793e869957126e0b5bbf",
          "sha256": "5fcb5e8bdd6b939207d9451a252ce838aa6d36b2b08c9945eade7f1f4e53bd01",
          "sha1": "6e18e2d51184a5009b572779adfdaae44259cecd",
          "md5": "663e268d627204d99f1a36b61d48186b"
        }
      ]
    }
  ]
}
