{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.9.3/json-schema-serialization-0.9.3.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.9.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-iosarm64-0.9.3.klib",
          "size": 85193,
          "sha512": "9a157e8d5f2a1e2c1dc9f50a3bfda102af643ad8a0ae3598fccc2abfe6213b283a89f83879b4e1485a5fb87984543d18574e2f6f631d5a77b9ca17021019c8fb",
          "sha256": "b1d07cc840d489122e0aac8aca97ab666d0140abeed595de8722970c785368bd",
          "sha1": "0363a500f59993fc27919ad260136d4d5a9ad261",
          "md5": "e302f1ac729e5a1943c00a2df974c1cf"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-iosarm64-0.9.3-metadata.jar",
          "url": "json-schema-serialization-iosarm64-0.9.3-metadata.jar",
          "size": 261,
          "sha512": "a806949053f14ff0727209546c4134a0e8284397368de99e9f5c0c2eeed5e3e95a9fed2fdbe7fb7f3b64de1d393450b4d1c3fdfa1c7e598104cda24a547ef1ce",
          "sha256": "db51f08c21c54f1e73e5f1228cea73669140aeee830f56c72d421dc73d6b3a64",
          "sha1": "4025c93e2531d47574195d5cb5c41192e4a818e5",
          "md5": "63523d85fec97fe1fc81d542eef41734"
        }
      ]
    }
  ]
}
