{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.15/json-schema-serialization-0.8.15.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-iosarm64-0.8.15.klib",
          "size": 73653,
          "sha512": "3786783f8dcdfeb1bc9b7c6d80ace9d51f52be56c0c3b078e92eb7fa5199aed47b5419b5a73be742c4bd4ebc00b8f9a03160dd78792c8d72ec71be86d9f67032",
          "sha256": "75a480dc5e1679d701dbb848e8f2be5f5432727bee4ecc35c43368a60279040d",
          "sha1": "a4e372064eed185c0c4c62a1c3b005a6c9e6db93",
          "md5": "00b11c5550c88638c5e2c0bfdae74975"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-iosarm64-0.8.15-metadata.jar",
          "url": "json-schema-serialization-iosarm64-0.8.15-metadata.jar",
          "size": 261,
          "sha512": "4f66d6a7eed9db69c297bfe098bf2fb18e25a8c77705160ec776cb1d5cea3ea98adfbef78a3a7244df329b1e50959673e87bf07ebcc44fa8c1e7af3cfafc2881",
          "sha256": "e3cba30350b99067393f4e82f7abdbdc2aa275c32307e26588896d40fad0b4f3",
          "sha1": "6f551d16a01f0c9cb7266e817df37deeec5e0fd6",
          "md5": "90bfec428905416f8930aa71017908d8"
        }
      ]
    }
  ]
}
