{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.9.0/json-schema-serialization-0.9.0.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-jvm-0.9.0.jar",
          "url": "json-schema-serialization-jvm-0.9.0.jar",
          "size": 168342,
          "sha512": "dce0156922149d2265993146965b1d483729ad76fc86d34f77d0c2db3f40382bfe74d8f2daa8e34cdcf781b44bb018f1b9765b0f3a6a37c9f072189dd87f2732",
          "sha256": "9c0d9c7f0d5177004c6e77a6c5e92770bd4e9373bf13d2baaaf489192c71d452",
          "sha1": "b5441a21b896cd56b5aeb463c4d13970bb39ada6",
          "md5": "09df508b62b95dfbe4c80b31b36734c4"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-jvm-0.9.0.jar",
          "url": "json-schema-serialization-jvm-0.9.0.jar",
          "size": 168342,
          "sha512": "dce0156922149d2265993146965b1d483729ad76fc86d34f77d0c2db3f40382bfe74d8f2daa8e34cdcf781b44bb018f1b9765b0f3a6a37c9f072189dd87f2732",
          "sha256": "9c0d9c7f0d5177004c6e77a6c5e92770bd4e9373bf13d2baaaf489192c71d452",
          "sha1": "b5441a21b896cd56b5aeb463c4d13970bb39ada6",
          "md5": "09df508b62b95dfbe4c80b31b36734c4"
        }
      ]
    }
  ]
}
