{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.27/json-schema-serialization-0.8.27.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-linuxx64-0.8.27.klib",
          "size": 76307,
          "sha512": "2751081f97b7fe85acddb6b8f7dbbc0635ce61cfed4d4e08a1e86fa4b02f144b081d94c0c3a167a797756de8061ff96165bc2ee6c1be5a009947e98a52faf34e",
          "sha256": "919f346ede9a8bed1ed54b423c0badb87e4cf8498a28fb5093cb7c8b2b570c4f",
          "sha1": "7fa4404379e3a0d951f4b1dcb208e10a61a13ecc",
          "md5": "ca3a3fae1282bddbebcae2b75f86e6ed"
        }
      ]
    }
  ]
}
