{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.19/json-schema-serialization-0.8.19.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-jvm-0.8.19.jar",
          "url": "json-schema-serialization-jvm-0.8.19.jar",
          "size": 143672,
          "sha512": "56046c1590018cfe96f3e169f7ce0298798e88b1593693cb6e6b132984b76e443e0d222946d03d0536ef4a8d81be1432ecc3fdd84272a720b1cded412d0e182b",
          "sha256": "c8c5b3895a80d9fa535965ae1bf1b364f0fc8141018012292e8ed60402d58108",
          "sha1": "0806b534a9931bcdd42a087d35d0a436fb4b7149",
          "md5": "06d3230bfcf7165ec43d1ce6374c976c"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-jvm-0.8.19.jar",
          "url": "json-schema-serialization-jvm-0.8.19.jar",
          "size": 143672,
          "sha512": "56046c1590018cfe96f3e169f7ce0298798e88b1593693cb6e6b132984b76e443e0d222946d03d0536ef4a8d81be1432ecc3fdd84272a720b1cded412d0e182b",
          "sha256": "c8c5b3895a80d9fa535965ae1bf1b364f0fc8141018012292e8ed60402d58108",
          "sha1": "0806b534a9931bcdd42a087d35d0a436fb4b7149",
          "md5": "06d3230bfcf7165ec43d1ce6374c976c"
        }
      ]
    }
  ]
}
