{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.22/json-schema-serialization-0.8.22.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-jvm-0.8.22.jar",
          "url": "json-schema-serialization-jvm-0.8.22.jar",
          "size": 150037,
          "sha512": "6d8852b4308f6123a1658601b827826df1322e5532be6fd4bcf14de70f6a0302a11f2c8355841c358b3c5d5184492ba2cbf2691fd05b697bef6b83a83f555f88",
          "sha256": "d98c8eab224d2069afce7df4267e16388b9ff6dcf5766bb56e12c81b28ea0886",
          "sha1": "da4613883e225c788627742c2fc2978c36521070",
          "md5": "03227c6955d5203821cee74bd51577be"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-jvm-0.8.22.jar",
          "url": "json-schema-serialization-jvm-0.8.22.jar",
          "size": 150037,
          "sha512": "6d8852b4308f6123a1658601b827826df1322e5532be6fd4bcf14de70f6a0302a11f2c8355841c358b3c5d5184492ba2cbf2691fd05b697bef6b83a83f555f88",
          "sha256": "d98c8eab224d2069afce7df4267e16388b9ff6dcf5766bb56e12c81b28ea0886",
          "sha1": "da4613883e225c788627742c2fc2978c36521070",
          "md5": "03227c6955d5203821cee74bd51577be"
        }
      ]
    }
  ]
}
