{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.0/json-schema-serialization-0.8.0.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-linuxx64-0.8.0.klib",
          "size": 71043,
          "sha512": "149938518667b2d6c38b87a995568e3dee96d51a2bd4ac7f1a1f91f3b2d2b85f8e15ee187c4187c7fcdbfd1b594c4ef1c7d5e330653e673a6ff694f67b7d1b1b",
          "sha256": "e123f273159b1e9756ef9d26664d98365ba6f1835e5f73d7c6215a9f8c31acc2",
          "sha1": "50d33e19a27075c51e8cf1005f4d493a795c9ccd",
          "md5": "18834e9cf2cab7ce66c171ff9c757cb3"
        }
      ]
    }
  ]
}
