{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.21/json-schema-serialization-0.8.21.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-mingwx64-0.8.21.klib",
          "size": 74135,
          "sha512": "91a9e734e9c3840868bf3d864f65908e2c84cf4be7093af2744c62c8ebbb86710973d385337a0847efc1c051e8a98af195e8288378e3bb39500e921699266466",
          "sha256": "5419ca6fb95e09370467447c25b9d9957672d747f9ad89ad0f97a8677465a289",
          "sha1": "f53d7916600978d5711231b9592d10082af1fe1d",
          "md5": "585d872ebee5dcd63062750c420edffc"
        }
      ]
    }
  ]
}
