{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.11/json-schema-serialization-0.8.11.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-linuxx64-0.8.11.klib",
          "size": 73715,
          "sha512": "6942475fcc304298a91ef27ef44bc9f76d14f31100af34cfcc1207ac0d6b7fe3b60ff545523631da5a6ff8c57e1927acd6ae6553f827f215763420c569e9e0b1",
          "sha256": "7fa4159a8f5c4006d18ca974706ef54a1c659da34f4d0b39f5cf9d026a11df29",
          "sha1": "45f19eea007bad5e9e1fce13014c2d63630e5a1d",
          "md5": "a156c6aed40b77f5aa7baf54bb5e071b"
        }
      ]
    }
  ]
}
