{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.9.6/json-schema-serialization-0.9.6.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.9.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-iosarm64-0.9.6.klib",
          "size": 85259,
          "sha512": "1bd616c94f21140b665064212883d96eb66822783beb25f5a5a34e86d3c493300f053e70764caa8628a30a16ab0d3e73e24bb5f00a32d8cc117e0189ad6cd53f",
          "sha256": "2a4649a2f918dade05acf438ece552185190e6816c597b08f42dcb30ac273681",
          "sha1": "44cb335379647fbff460030d93f07cfee25dbd34",
          "md5": "6299ed91859134a96104a7791f02eb22"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-iosarm64-0.9.6-metadata.jar",
          "url": "json-schema-serialization-iosarm64-0.9.6-metadata.jar",
          "size": 261,
          "sha512": "512e5098b81fcbc45ef48a92f3f48d1ad04b880299e87d5b232b235487ba5234d2e22ae132bbadbdf68f63f990dee4df2b0d93d33229d58a8b925f31ac0a259c",
          "sha256": "fc33ad65ca77a77ee65c6a4f9d026762c4868f6aeb99ad685b1e38074f77ee89",
          "sha1": "ed561dab63039ac3f9790377cec54b033a798d5c",
          "md5": "bc6dfd5c2e24bcc73c185747a75522d9"
        }
      ]
    }
  ]
}
