{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.9/json-schema-serialization-0.8.9.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-linuxx64-0.8.9.klib",
          "size": 73437,
          "sha512": "48f96f49a92f0076eb355280e5ecad19ff89997e3b0a927c94e7fe1c2692d0c2607344379211bfb45501758674d7a8e7bea9f5c5a6216115448f9945c0f6d9c2",
          "sha256": "ee75cbd889f17e0a3a6287f80d7b7ed8ac501b7d9414a1fc4597de4c71b839b9",
          "sha1": "8f603a70bf9bd7f10baf84805290bf580709acb7",
          "md5": "d80ce9111e155999438d4c7e14efb943"
        }
      ]
    }
  ]
}
