{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.5/json-schema-serialization-0.8.5.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-linuxx64-0.8.5.klib",
          "size": 71353,
          "sha512": "efa95101b88c606e896f2af55d625e30974b4ef8f352bf5440fed9132a23fc616e33dd986283053df892c5dd890e2ea9d3406bf610571ea5df8635ae5b650afa",
          "sha256": "fa219037563a7ffb02e8759a3c191f395d5797760f9eb2845f49e14f9b6f4741",
          "sha1": "281faaeae390f5021ab3341a0727b79bd15d03c5",
          "md5": "2cd092a1b485d3cbeb2cf09d941633d6"
        }
      ]
    }
  ]
}
