{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.14/json-schema-serialization-0.8.14.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-jvm-0.8.14.jar",
          "url": "json-schema-serialization-jvm-0.8.14.jar",
          "size": 143760,
          "sha512": "4f82b9128ff250ec1f3dc37d91968025e7da91a9b684d9b90fe46c039ab976628680c31329acbf3d3a4479fec975b6d5bb38de809c061c8050b3cb503ad6f5f3",
          "sha256": "cfa809507e0aaa75a0351431f77421c7f01318eaecc0540548cb7b307370677a",
          "sha1": "85ce459d63851c37a729ebb2246e8dcd7677128d",
          "md5": "a90269e7065d92242dd640883391abf2"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-jvm-0.8.14.jar",
          "url": "json-schema-serialization-jvm-0.8.14.jar",
          "size": 143760,
          "sha512": "4f82b9128ff250ec1f3dc37d91968025e7da91a9b684d9b90fe46c039ab976628680c31329acbf3d3a4479fec975b6d5bb38de809c061c8050b3cb503ad6f5f3",
          "sha256": "cfa809507e0aaa75a0351431f77421c7f01318eaecc0540548cb7b307370677a",
          "sha1": "85ce459d63851c37a729ebb2246e8dcd7677128d",
          "md5": "a90269e7065d92242dd640883391abf2"
        }
      ]
    }
  ]
}
