{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.11/json-schema-serialization-0.8.11.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-jvm-0.8.11.jar",
          "url": "json-schema-serialization-jvm-0.8.11.jar",
          "size": 143904,
          "sha512": "9db20bbfa4c01a6e7047fdce08fecb66cdb633e05293f377a34737432a05cdc23a768d354f51ff22220ab3801c51663cd9377110f678402aaa5b5fbc79180359",
          "sha256": "f3ed9bcaff6a54a7bd3c53a7b6a242b272d7185b0bd25a57ce48209bf77c62ac",
          "sha1": "f37002eff02cb4ed6a966cb93d321b5226399f57",
          "md5": "2ac8e2552b6cf8a591aee6d6a38d4ed8"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-jvm-0.8.11.jar",
          "url": "json-schema-serialization-jvm-0.8.11.jar",
          "size": 143904,
          "sha512": "9db20bbfa4c01a6e7047fdce08fecb66cdb633e05293f377a34737432a05cdc23a768d354f51ff22220ab3801c51663cd9377110f678402aaa5b5fbc79180359",
          "sha256": "f3ed9bcaff6a54a7bd3c53a7b6a242b272d7185b0bd25a57ce48209bf77c62ac",
          "sha1": "f37002eff02cb4ed6a966cb93d321b5226399f57",
          "md5": "2ac8e2552b6cf8a591aee6d6a38d4ed8"
        }
      ]
    }
  ]
}
