{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.16/json-schema-serialization-0.8.16.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-jvm-0.8.16.jar",
          "url": "json-schema-serialization-jvm-0.8.16.jar",
          "size": 143656,
          "sha512": "cab0645ea498bd8ec386350dc7b3d9a1c4ae44ffaaddd8920a5a0a492a2163f197c25bf1e68135b84c73ebfe281c7eaf31ba8b575ce33dd9ac3fbce0ffc84b76",
          "sha256": "00a16fe4d26566ad97f22fe3fc21608b8d8478134b4fd94a54276d62f7d2ff63",
          "sha1": "68fa4b9c695bff284f27b5dbca96d39c2dd25694",
          "md5": "d7948515513c227606a273009ecefe05"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-jvm-0.8.16.jar",
          "url": "json-schema-serialization-jvm-0.8.16.jar",
          "size": 143656,
          "sha512": "cab0645ea498bd8ec386350dc7b3d9a1c4ae44ffaaddd8920a5a0a492a2163f197c25bf1e68135b84c73ebfe281c7eaf31ba8b575ce33dd9ac3fbce0ffc84b76",
          "sha256": "00a16fe4d26566ad97f22fe3fc21608b8d8478134b4fd94a54276d62f7d2ff63",
          "sha1": "68fa4b9c695bff284f27b5dbca96d39c2dd25694",
          "md5": "d7948515513c227606a273009ecefe05"
        }
      ]
    }
  ]
}
