{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.9.1/json-schema-serialization-0.9.1.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization.klib",
          "url": "json-schema-serialization-iossimulatorarm64-0.9.1.klib",
          "size": 84890,
          "sha512": "dcac75e088fb0cf0d5efd524869b9560f7173a5228cb4ef54e1fca1492556fd23c8cfaff960ac3389b77503dd34d07babb4ed1d9437238ed410623c7959b0f31",
          "sha256": "6dafc97f09e2292f86d8479fd1bc947a507ac8f94fea4980bfa80fe30699d245",
          "sha1": "c81ac48e149100fde9e804074b2701177f77df60",
          "md5": "fdf00d1fb8c2c1435a5b1acb00f7b05c"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-iossimulatorarm64-0.9.1-metadata.jar",
          "url": "json-schema-serialization-iossimulatorarm64-0.9.1-metadata.jar",
          "size": 261,
          "sha512": "56f098a3a9be7cfc578dc429eac95b9d9c7f71e072846b21b680bab7935414c1ea7b126ed58726503b93b75331954d3e86d8b1145477e28c632340570777b8ce",
          "sha256": "b4ece37ca9756514ea1334fac33cb15340d11584d1cd52f303175084727e8c85",
          "sha1": "55e274967042d5e4ede6ebd8b7a189cfcae4c200",
          "md5": "0748d3b51eda482561ddb6c4549e13bf"
        }
      ]
    }
  ]
}
