{
  "formatVersion": "1.1",
  "component": {
    "url": "../../json-schema-serialization/0.8.29/json-schema-serialization-0.8.29.module",
    "group": "com.github.Ricky12Awesome",
    "module": "json-schema-serialization",
    "version": "0.8.29",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-jvm-0.8.29.jar",
          "url": "json-schema-serialization-jvm-0.8.29.jar",
          "size": 153470,
          "sha512": "4314db5a0a9404a9bf56d05f5bcd22d666b0b8aa7fad23dd6e857b850e46aa4a34ee6836c1a835c9400a00edb613535af9de0fd9f003d9c7d3acb6893e7a7ea1",
          "sha256": "ad6be3437a5a5ce1e3075f4079909a23ae24b279bda3e847806514fcbe7f5260",
          "sha1": "89b1f7a78fb820f95089f952b48ce7cd91c2417c",
          "md5": "da4b62b583b7b26adc49d2dc87fe52ce"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-schema-serialization-jvm-0.8.29.jar",
          "url": "json-schema-serialization-jvm-0.8.29.jar",
          "size": 153470,
          "sha512": "4314db5a0a9404a9bf56d05f5bcd22d666b0b8aa7fad23dd6e857b850e46aa4a34ee6836c1a835c9400a00edb613535af9de0fd9f003d9c7d3acb6893e7a7ea1",
          "sha256": "ad6be3437a5a5ce1e3075f4079909a23ae24b279bda3e847806514fcbe7f5260",
          "sha1": "89b1f7a78fb820f95089f952b48ce7cd91c2417c",
          "md5": "da4b62b583b7b26adc49d2dc87fe52ce"
        }
      ]
    }
  ]
}
